### ISSUE TITLE
move the cache.py config file into the storage.py file

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#101]

**Comment by clsource** [comment]
I need more clarification 👍

**Comment by josephmancuso** [comment]
Sorry I really just mean move the contents of cache.py into storage.py. not making it their own packages

**Comment by clsource** [comment]
But they have constants with name collision.
They should be renamed?

**Comment by josephmancuso** [comment]
oh true .. 🤔 hmm ok. then nvm we can keep it lol

**Comment by clsource** [comment]
lol
