### ISSUE TITLE
Improve Craft commands with Snippets

### ISSUE THREAD

**Issue by clsource** [MasoniteFramework/masonite#103]
Some commands like Auth create the files using some blueprints files

https://github.com/MasoniteFramework/core/blob/58db21ad648fff91ef45b7ae7778515969654cc2/masonite/commands/AuthCommand.py#L30

Other commands like new command use only inline text.

https://github.com/MasoniteFramework/core/blob/58db21ad648fff91ef45b7ae7778515969654cc2/masonite/commands/CommandCommand.py#L23

In order to standarize and modularize. all commands that create new files or directory structures should use snippets aka blueprints for their base output.

These blueprints should be Jinja2 valid files in order to replace any placeholder. But this will depend on the package creator design.

The base structure for snippets would be

```
app/
   resources/
     snippets/
         commands/
                        <command_namespace>/
                                                            file1....n
```

This structure would be inside the user's masonite directory and not the package.
This would improve the flexibility since the user could modify such blueprints as needed without touching the original blueprint files.

the `<command_namespace>` is the name of the command as used in craft. And it's contents would be the same as the available in the `snippets/` directory of the package.

The idea is having a helper function that loads a file first from the app's snippets directory and if not found then loads the package's snippets directory. In that way the command would still work if no file is found.

Implementing this is totally optional to the package creator. If it is desired to give the user the option to customize the command blueprints.

**Comment by josephmancuso** [comment]
woah this is an awesome idea although it should be tweaked. 

What i suggest is that we keep it into the core repository. This way we can make any changes we need to between minor releases. We learned this the hard way during 2.0 release where the wsgi.py file was all messed up.

I say we keep it in core but we create a:

```
craft publish
```

command to basically put the snippet that the core repo is using inside the resources folder and we do something like:

```
if View.has('/app/resources/snippets/whatever'):
    use that
else:
    use /masonite/snippets/whatever
```

This way they can change the type of controllers or models that are created like you suggested.

It could be used like:

```
craft publish command_name
```


maybe something like that?

**Comment by josephmancuso** [comment]
this way people might want to craft different types of models everytime they craft a model like models that inherit from a different class or import various things

**Comment by josephmancuso** [comment]
the craft publishc ommand will basically move it from the core and into the project which masonite will then pickup

**Comment by clsource** [comment]
I believe for built in commands
something like

`$ craft install:snippets`

would create the snippets directory filled with all the blueprints for standard commands
And for third party commands the

`$ craft install:<package-namespace>` would be left for the package creator
to create the snippet directory that fits to their needs.

If people would like to use another blueprint for example models
a simple option would be enough.

`--s|snippet Will use the desired snippet`

`$ craft model -s User.py`

The command would look inside the `/resources/snippets/model/` for a file named `User.py` and used instead of the default model snippet. 

👍

**Comment by clsource** [comment]
Cool 👍 
The default file extension for snippets would be `html`?
I think that should be defined by each command. 

So the controller creator  would look for py files or another as default extension.

Example usages for the Model Command

`$ craft model User` : Traditional model usage with default template and default path
`$ craft model /path/User -s`: Will create a model named User in the desired path and look for a snippet called User.py or user.py
`$ craft model User.extension -s`: Will create a model named User and look for snippet called User.extension or user.extension
💯
