### ISSUE TITLE
Regular "class method", or a regular method?

### ISSUE THREAD

**Issue by AndersenTobias** [MasoniteFramework/masonite#107]
From the docs (https://docs.masoniteproject.com/the-basics/controllers):
> Controller methods are very similar to function based views in a Django application except this is just a normal **class method**. Our controller methods at a minimum should look like:

```
def show(self):
    pass
```

> All controller methods must have the self parameter. The self parameter is the normal python self object which is just an **instance of the current class as usual**. Nothing special here.

(Emphasis mine)

I don't see a `@classmethod` decorator being used here. Very confusing, please fix.

**Comment by josephmancuso** [comment]
looking into this now :)

**Comment by josephmancuso** [comment]
not sure what you are getting at with this line?

> All controller methods must have the self parameter. The self parameter is the normal python self object which is just an instance of the current class as usual. Nothing special here.

What part is confusing?

**Comment by josephmancuso** [comment]
maybe something like this is better?

> All controller methods must start with the self parameter. The self parameter is the normal python self object which is just an instance of the current object as usual. Nothing special here.

**Comment by AndersenTobias** [comment]
Sorry for the delay, I'm not very active on Github. :)

> What part is confusing?

To answer your specific question, I think that "instance of the current class" is a bit vague as classes are first-class objects in Python. Given that you wrote "class method" a bit earlier, I was expecting you to explain the `cls` convention, which, as you know, should refer to the current class...

The more general question is: why are you elaborating on the `self` parameter at all? Your audience are Python programmers already, and so you might as well drop the second sentence entirely:

> All controller methods must start with the `self` parameter. Nothing special here.

But yes, your updated version ("instance of the current object as usual") is also good, and much clearer than the original version.

Feel free to close this issue whenever you think this has been resolved.

**Comment by josephmancuso** [comment]
> Your audience are Python programmers already, and so you might as well drop the second sentence entirely:

Although i do agree, not all are Python programmers. Some are coming from Ruby or PHP because of the similarities in the framework and ORM.

But I think you're right. I'll drop the second sentence entirely since any Python 101 tutorial will teach them that.
