### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Jasmine2** [MasoniteFramework/masonite#118]
How could i send a json response on middleware ?
I tried return and exception , but not run.

**Comment by josephmancuso** [comment]
Not sure what you are asking 🤔 

How do you return a JSON response?

just return a dicitonary

**Comment by josephmancuso** [comment]
you cannot (and should not) return responses in a middleware. That's not what middleware is designed to do.

**Comment by josephmancuso** [comment]
yeah you can't return a response in a middleware. You should return responses in controllers

**Comment by josephmancuso** [comment]
what are you actually trying to accomplish? There is likely an easier way to do what you are trying to do

**Comment by josephmancuso** [comment]
if you want better assistance you can join the slack channel and ask there: https://slack.masoniteproject.com

**Comment by Jasmine2** [comment]
In fact, I want to return a json object when the request is ajax and the authorization fails
