### ISSUE TITLE
architecture tree

### ISSUE THREAD

**Issue by who-am-1** [MasoniteFramework/masonite#124]
**Model**: app/Post.py
**View**: resources/templates/blog.html
**Controller**: app/http/controllers/ControllerClassName.py
**Urls**: routes/web.py

I just want to say, I am puzzled. I can't found the logic in the location of the directory tree, after reading 'creating your first blog'. It's super strange and incomprehensible. After this, Django architecture seems like a super logic.

**Comment by hammacktony** [comment]
Can you elaborate more on your issue?

**Comment by hammacktony** [comment]
If you so choose, you can visit https://masoniteproject.slack.com and talk directly with the devs.

**Comment by josephmancuso** [comment]
So all *controllers* are in `app/http/controllers`
All *models* are wherever you like them to be. They are in `app/` by default but feel free to move them into `app/models`
all *views* are in `resources/templates`. Views in Masonite are just html files as opposed to how Django makes them python functions or classes (FBV's and CBV's).

URL's go into `routes/web.py`

****

Masonite uses a conventional MVC architecture. Django uses MTV. Slightly different interpretation of the 3 out of 4 architectural patterns (Business Logic, Presentation Logic, Data Accession Logic). 

You MAY need a mild understanding of MVC to understand Masonite but most dev's find it's fairly straight forward to understand but feel free to drop any questions here or in Slack for a further understanding.

https://slack.masoniteproject.com to get an invitation to the slack channel

**Comment by who-am-1** [comment]
You are have now something like that:
```
site_name/
    site_name/
        .env
        wsgi.py
        tests/
        ...
        app/
            Blog.py
            http/
                controllers/
                    Blog.py
        resources/
            templates/
                blog.html
```
        
What's mean http into this?

Masonite not support multiple apps? I mean something like that (just suggested blueprint):
```
site_name/
    .env
    wsgi.py
    url.py
    static/
    tests/
    index.py #controller
    model/
        migration/
        index.py
    view/
        index.html
    ...
    app/
        blog/
            .env
            url.py
            blog.py #controller
            model/
                migration/
                blog.py
            view/
                blog.html
                post.html
            static/
            tests/
            ...
        forum/
            .env
            url.py
            forum.py #controller
            model/
                migration/
                forum.py
            view/
                forum.html
            static/
            tests/
            ...
```

**Comment by josephmancuso** [comment]
You don’t need multiple apps. It’s an MVC architecture. You would instead abstract controllers into their own modules. Django has the concept called apps to house all of your logic. Masonite has controllers to separate business logic. It’s a different architecture and file structure than Django. (Although feel free to restructure Masonite as you like) Many devs really like the file structure. Some do not like it. Maybe it takes some getting used to but it is very organized either way

**Comment by who-am-1** [comment]
It seems that this is not suitable for me. I tried to understand, but I could not. This is probably good for a JS programmer. In my case, this is kill my brain. It's not logical. I will continue to use the Django/Flask-based frameworks.

**Comment by josephmancuso** [comment]
possibly watching a youtube series may help: https://www.youtube.com/playlist?list=PLdR9bD5hyZiiPv3pmtkSbFOFTE2HIVmhl

**Comment by vaibhavmule** [comment]
I'm from Django background and I know Masonite will be intimidating at
first. Of course, the architecture  might not be familiar. That is
because Masonite
comes with the learning curve if you are not coming from a background of a
framework like Rails, Laravel, Phoenix, to understand about Masonite in the
depth, you have to go through it, then get hang of it.

Any framework has its own philosophy, so does Masonite. A blog example or
even initial folder structure will not convey the message what Masonite
wants to offer as we (Django devs) made our mind that some things should be
the way how it should be not the other way around.

I would suggest,

Try building a simple clone of Twitter or Pinterest or something like that
which makes full use of any web framework.

After that, if you will have better judgement, You might find that Masonite
and Django have the different use cases and you might use the framework
accordingly.
