### ISSUE TITLE
Variable naming ambiguity 

### ISSUE THREAD

**Issue by Gwill** [MasoniteFramework/masonite#132]
https://github.com/MasoniteFramework/masonite/blob/master/wsgi.py#L20

How about `container.bind('ApplicationConfig', application)`?

https://github.com/MasoniteFramework/masonite/blob/master/bootstrap/start.py#L16

How about `def wsgi_app` ?

**Comment by josephmancuso** [comment]
that is the application configuration found in `config.application`.

**Comment by josephmancuso** [comment]
also binding modules to the container will be deprecated in 2.1
