### ISSUE TITLE
orator has `autocommit` error

### ISSUE THREAD

**Issue by tonyjia87** [MasoniteFramework/masonite#138]
https://github.com/sdispater/orator ,this repo last  commit is bd90bf198ee897751848f9a92e49d18e60a74136 . But  [Merge pull request #235 ](https://github.com/sdispater/orator/commit/80c0902fe9753c0372308b7708a63391d2de1b55) code :  
```
def __enter__(self):
        self._reconnect_if_missing_connection()
        self.begin_transaction()

        return self
```

I user `pip install -r requirements.txt`,find code `orator/connections/connection.py`

```
    def __enter__(self):
        self.begin_transaction()

        return self


```

According to my experience, there will still be problems。

**Comment by josephmancuso** [comment]
yes i am guessing that orator is not yet released a version with that fix yet

**Comment by tonyjia87** [comment]
> yes i am guessing that orator is not yet released a version with that fix yet

This is a very dangerous thing, but it is not masonite  problem. If it is you will solve it ？

**Comment by josephmancuso** [comment]
Yes i'll reach out to sdispater. I don't have authorization to currently do releases yet. Thanks for the report

**Comment by josephmancuso** [comment]
just messaged him
