### ISSUE TITLE
&lt;p&gt;test&lt;/p&gt; not render 

### ISSUE THREAD

**Issue by 1to10** [MasoniteFramework/masonite#155]
&lt;p&gt;test&lt;/p&gt; not render <p>test</p> from mysql when we retrive as variable by safe method
not render in view it print

**Comment by 1to10** [comment]
&lt;p&gt;test&lt;/p&gt; from mysql when we retrive as variable by safe method
 not render in view it print <p>test</p>

**Comment by josephmancuso** [comment]
Can I see your code? If you are using the request method to get the input then you will need to add a clean=False to the input method

**Comment by josephmancuso** [comment]
https://docs.masoniteproject.com/the-basics/requests#input-cleaning

**Comment by 1to10** [comment]
ok working. Thanks.
