### ISSUE TITLE
Updating pendulum

### ISSUE THREAD

**Issue by damdinsharav** [MasoniteFramework/masonite#160]
Hello,
I was having error with following code.
```
import pendulum

dt = pendulum.from_format('20191005070000', 'YYYYMMDDHHmmss')

print(dt)
```

Then I installed just Pendulum in new environment and my code worked.

After digging a little it seems this bug has been fixed in Pendulum 2.0.1 

> Fixed behavior of the YY token in from_format().

**Comment by josephmancuso** [comment]
Orator will currently not work with 2.0 versions of pendulum yet which is why Masonite is fixed to the latest 1.x version. Will need to fix that in orator but that’s a breaking change. Try the parse method maybe?
