### ISSUE TITLE
Can't use 'craft new .'

### ISSUE THREAD

**Issue by yashaslokesh** [MasoniteFramework/masonite#162]
Hello, I can't use the command `craft new .` listed [here](https://github.com/MasoniteFramework/masonite#installation-1), in the Hello World section of the README. 

Output: 
```
$ craft new .
Directory . already exists. Please choose another project name
```

I'm running this on macOS Catalina, v 10.15
Python version 3.7.4
Pip version 19.2.3

**Comment by nioperas06** [comment]
Hello @yashaslokesh. I think it's a typo. You should do something like:
```
$ craft new project_name .
```

**Comment by josephmancuso** [comment]
updated docs thanks to @nioperas06
