### ISSUE TITLE
issue 502 bad gateway

### ISSUE THREAD

**Issue by 1to10** [MasoniteFramework/masonite#164]
i have issue in application with 
![SAVE_20191018_103008](https://user-images.githubusercontent.com/9332876/67067558-64cb2700-f194-11e9-8215-ff3635b3b265.jpeg)
502 bad gateway after craft install it work perfectly.

**Comment by 1to10** [comment]
please give me suggestion.

**Comment by 1to10** [comment]
please reply me sir.

**Comment by josephmancuso** [comment]
This looks like a web server issue. Are you using nginx

**Comment by josephmancuso** [comment]
You will need to look at your web servers error logs and see what the actual issue is
