### ISSUE TITLE
Masonite Homepage

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/masonite#175]
Here is repo: https://github.com/MasoniteFramework/masoniteframework.github.io

Creating this issue for discussion related to the landing page of Masonite Framework 

Suggestions, feedbacks are welcome.

**Comment by josephmancuso** [comment]
If anyone is willing to code something up. Can be simple html / css.

Help is wanted

**Comment by girardinsamuel** [comment]
I will do it ;)
- [ ] link back from https://docs.masoniteproject.com/ to masoniteframework.github.io
- [ ] link back from http://slack.masoniteproject.com/ to masoniteframework.github.io
- [ ] @josephmancuso should we correct HTTP->HTTPS redirection on slack.masoniteproject.com or should we change the link to Slack on masoniteframework.github.io because right now it is broken ?

By the way great work @vaibhavmule !

**Comment by josephmancuso** [comment]
@girardinsamuel no because https is not setup on the server

**Comment by girardinsamuel** [comment]
@josephmancuso 
- Okay, not a big deal ! @vaibhavmule, I opened a PR to correct the link to HTTP if you want.
- for https://docs.masoniteproject.com/ we could update the headers links of the doc (through GitBook) to get that :
![image](https://user-images.githubusercontent.com/9897999/68980955-3af03900-0802-11ea-81b6-eaa0ae2e5003.png)

**Comment by girardinsamuel** [comment]
Hi everyone, 
What is the status for this issue ? 
I made a PR to slackinvite : https://github.com/MasoniteFramework/slackinvite/pull/1
I proposed a change for masonite documentation (see previous comment) but I cannot modify GitBook config myself.

Thanks 👍

**Comment by josephmancuso** [comment]
yeah the top nav part is a gitbook config i'll need to add. Also the slackinvite site was deployed using a personal service I created which is currently under redevelopment. So when i redeploy that site i'll deploy the slack site

**Comment by girardinsamuel** [comment]
> yeah the top nav part is a gitbook config i'll need to add. Also the slackinvite site was deployed using a personal service I created which is currently under redevelopment. So when i redeploy that site i'll deploy the slack site

Hi @josephmancuso, wondering if you have time to add Masonite Framework Home (masoniteframework.github.io) link in gitbook doc header  ?
Feel free if I can help on this issue !
