### ISSUE TITLE
Add mailable html template snippets

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#176]
We should be able to build emails really quickly by doing something like:

```html
{% import 'masonite/email' as component %}

{% component.header('Thanks for the email!') %}

{% component.button('Take Action', color="danger") %}
```

**Comment by stuart-haas** [comment]
@josephmancuso I’m new to Masonite and have recently started building a web app with it. I really like what you’ve done here, and much credit to all those who have contributed as well. I’d like to make contributions as well. Could you expand on what you are looking for regarding this enhancement? I was looking through the docs and didn’t see anything about template components like headers or buttons. Should this be something that could be generated through the cli?

**Comment by josephmancuso** [comment]
@stuart-haas i'm not really sure to be honest which is why I never completed the issue. It's always grown stale. It was almost 2 years ago I made this issue and it was prob a random thought I had on my way home from work. 

With that being said I think what I think I was thinking at the time is that there should be some kind of quick "components" to build up simple templates. The syntax above looks a lot like I was thinking of Jinja's Macro's where you can make an HTML template and then being able to import and use it like above? https://jinja.palletsprojects.com/en/2.11.x/templates/#macros

**Comment by girardinsamuel** [comment]
I guess this could be achieved more easily with next major release M4
