### ISSUE TITLE
Select replacement for sass compiling

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#177]
Need to remove the SassProvider and other tests since we are removing the libsass abilities from Masonite 2.3.

This should be removed in favor of something like laravel mix

**Comment by kharysharpe** [comment]
Came across this some time ago, maybe worth comparing with mix.

https://symfony.com/doc/current/frontend.html#webpack-encore

**Comment by josephmancuso** [comment]
Development on this is finished. Now can research replacement options

**Comment by josephmancuso** [comment]
And once we find a solution, whats the best way to implement this. Do we have npm come default now?

**Comment by carc1n0gen** [comment]
I'm very much in favour of laravel mix over any alternative

**Comment by josephmancuso** [comment]
Added mix to the cookie-cutter repo `2.3` branch which will be used for 2.3+ https://github.com/MasoniteFramework/cookie-cutter
