### ISSUE TITLE
No module named 'orator'

### ISSUE THREAD

**Issue by ashfaqahmed** [MasoniteFramework/masonite#179]
Hello, i am just getting start with it via following the documentation, when creating migration for post table as per the documentation `"craft migration create_posts_table --create posts"` this gives the error `No module named 'orator'`.

I have verified installation for orator using 
`pip3 install orator` 
and also
`pip3 install --upgrade masonite-cli`
It say's

"Requirement already satisfied." so i am stuck here on the documentation no-way to proceed further.

Please suggest.

**Comment by josephmancuso** [comment]
are you using a virtual environment?

**Comment by ashfaqahmed** [comment]
> are you using a virtual environment?

Yes i am using virtual environment python3

**Comment by josephmancuso** [comment]
hmm i haven't seen that issue before

**Comment by josephmancuso** [comment]
did you install craft globally or only inside your virtual environment?

**Comment by ashfaqahmed** [comment]
> craft

Its installed at both-sides as globally and also inside virtual environment.

**Comment by ashfaqahmed** [comment]
Also have tried this with `python craft migration create_posts_table --create posts`
<img width="734" alt="Screen Shot 2019-11-04 at 4 54 03 AM" src="https://user-images.githubusercontent.com/2121712/68094999-33a26480-febf-11e9-865b-8909e52e95d5.png">

**Comment by josephmancuso** [comment]
try to uninstall it globally. might be conflicting with eachother

**Comment by ashfaqahmed** [comment]
Uninstalled from machine level, uninstalled from virtual environment, re-installed inside virtual-environment still same issue persist.

**Comment by ashfaqahmed** [comment]
Uninstalled everything, deactivated virtual environment and installed from scratch as a globally not inside virtual environment, it worked well as globally, not sure what kind of issue is with virtual environment.

Thanks for the help :)

**Comment by josephmancuso** [comment]
lol not sure. So everything is good now?

**Comment by ashfaqahmed** [comment]
> lol not sure. So everything is good now?

Yes working fine now, i will have a try on virtual-environment again next time :)
