### ISSUE TITLE
Controller/View Naming in Auth Scaffolding

### ISSUE THREAD

**Issue by erikwestlund** [MasoniteFramework/masonite#182]
**Is your feature request related to a problem? Please describe.**
Naming issue.

**What do we currently have to do now?** 
I think naming of controllers could be improved.

**Describe the solution you'd like**
The file `ConfirmController` would be better named as `EmailVerificationController` as confirm is not the verb used in other classes (e.g., `MustVerifyEmail`). I'd pick "verify" or "confirm" and stick with that verb throughout.

I also think in general the view file names could have better, more descriptive filenames. Such as

"verify-email-message"
"password-reset-request"
"password-reset"

**Comment by girardinsamuel** [comment]
Ready for review #217 !

**Comment by girardinsamuel** [comment]
Hi !
Got time now to work on Masonite again ! Should I transfer #217 onto the new release 2.3 of Masonite as it was not merged last time ?

Thanks !

**Comment by josephmancuso** [comment]
@girardinsamuel does this still need to be done in M4?
