### ISSUE TITLE
craft new project shows an urlerror

### ISSUE THREAD

**Issue by J88G** [MasoniteFramework/masonite#185]
**Describe the bug**
After create a virtualenv with Python3.7, install masonite-cli. 
When I run `craft new project` I got:

craft new project
Crafting Application ...
  [URLError]
  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c :1056)>

new [-b|--branch BRANCH] [-r|--release RELEASE] [--] <name> [<target>]

Desktop :
 - MacOs

**Comment by nioperas06** [comment]
Maybe this: [https://stackoverflow.com/a/50265045](https://stackoverflow.com/a/50265045)
