### ISSUE TITLE
Create a tutorial to create an api

### ISSUE THREAD

**Issue by J88G** [MasoniteFramework/masonite#186]
**What do we currently have to do now?** 
At the moment you only have a video on youtube from version 1.5

**Describe the solution you'd like**
A clear tutorial with the basic of an api, and how to integrate it with billing and other resources.

**Describe alternatives you've considered**
A video, or a documentation

**Comment by josephmancuso** [comment]
I recently did a live call with a meetup in Jamaica where I walked through setting up factories, seeds and walked through how to create a basic CRUD endpoint with tests.

I'll release that when I get the copy

**Comment by ulgens** [comment]
Isn't it better to close this issue when the content is released @josephmancuso ?

**Comment by josephmancuso** [comment]
thats fair

**Comment by josephmancuso** [comment]
https://www.youtube.com/watch?v=-rxBJ9JzLtc
