### ISSUE TITLE
Add ability to download and display files from the controller

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#188]
**Is your feature request related to a problem? Please describe.**
We need to be able to download files from the web. We may do something like generate PDF's and then need to be able to force that download (or display it in the browser)

**What do we currently have to do now?** 
We simply cannot do it now

**Describe the solution you'd like**
We need something like this in the controller:

```python
from masonite.helpers import Download

def show(self):
     return Download('/some/file.pdf')
```

This will display it properly in the browser. We should also be able to force the download:

```python
from masonite.helpers import Download

def show(self):
     return Download(open('/some/file.pdf'), force=True)
```

or 

```python
from masonite.helpers import Download

def show(self):
     return Download('/some/file.pdf').force()
```

- [x] Is this a breaking change?

**Additional context**
This will entail moving away from compiling everything to string (and then bytes at the end) to converting everything to bytes.

This will also require a change to the start.py file.

**Comment by nioperas06** [comment]
I know that we can do something like this `from masonite.helpers import Download as download` but I definitely prefer helpers starting with lowercase character. Ex: `compact`, `collect`, etc

**Comment by josephmancuso** [comment]
That’s fair. I like it

**Comment by josephmancuso** [comment]
After implementing I thought it would be better to put it on the response namespace. So now it will look like this:

```python
from masonite.response import Download

def show(self):
    return Download('path/to/file').force()
```

**Comment by girardinsamuel** [comment]
Should we also implement/use this new type of response to download file linked to a model ?

**Comment by josephmancuso** [comment]
Hmm how would you link a file to a model?

**Comment by girardinsamuel** [comment]
I was thinking of a model in the Masonite meaning linked to a database table, where one of the field/column is a file path but actually I realize it will just be a simple CHAR column. And this way it's the same as trying to download a file with its path by using `Download('path/to/file')`. (I was thinking with the Django background where you have a model with the FileField (given by Django ORM)).

So I guess as it's not the same ORM philosophy there is no need for that. However does it mean that we have to handle media path upload ourself, or is there a way to define for example, that all uploads are going to a media root folder (as in Django) ?

**Comment by josephmancuso** [comment]
@girardinsamuel I think if we go that route we would need to open a dedicated issue for that but I think we should approach something like that in the near feature. Preferably after 2.3 is released. Since this is staged in 2.3 I'll close this
