### ISSUE TITLE
Status Code don't setting up when uses request.status(STATUS_CODE)

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/masonite#220]
**Describe the bug**

When this following snippet is ran to change the status code from Request object, the current response don't is changed.

```python
this.request.status(400)
this.response.json(json_data)
```

**To Reproduce**
1. Create a controller and put the following snippet inside it:

```python
this.request.status(400)
this.response.json(json_data)
```
**Expected behavior**
The response's status should be 400 but was 200 OK.

**Screenshots**

> Console response it's ok.
![Sem título](https://user-images.githubusercontent.com/4117999/71316413-f9305f00-244d-11ea-92a5-d5c66d7aed99.png)

> Browser response isn't ok.
![test](https://user-images.githubusercontent.com/4117999/71316414-f9305f00-244d-11ea-8c3e-7f6bb52b65c8.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version 79.0

**Comment by josephmancuso** [comment]
ah yes if you are using the response class directly it has a status code on it already 

```python
this.response.json(json_data, status=400)
```

**Comment by carc1n0gen** [comment]
setting response status code on request feels backwards anyway

**Comment by josephmancuso** [comment]
right, there's a few methods on the request class for pure convenience. Like getting the user from the request where you can also get it on the authentication class (which makes more sense). So thats why it is on there. If we make a way to set it in the controller more easily we can deprecate this method.

Thinking of maybe doing something like this:

```python
def show(self):
    return {'key': 'missing'}, 404
```

basically returning a tuple which isn't a terrible idea
