### ISSUE TITLE
Returning a tuple should set the status code

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#222]
**Is your feature request related to a problem? Please describe.**
Should be an easy way to set the status code in a controller

**What do we currently have to do now?** 
Currently we can set the status code in 2 ways, 1 on the request and 1 on the response.

**Describe the solution you'd like**
A good approach will be to return a tuple like this:

```python
def show(self):
    return 'record not found', 404

**Comment by Marlysson** [comment]
This feature should be done in this repository or `core` one?
