### ISSUE TITLE
ValueError > Invalid salt in LoginController on line 52 with PostgreSQL

### ISSUE THREAD

**Issue by holic-cl** [MasoniteFramework/masonite#227]
**Describe the bug**
I moved driver database from MySQL to PostgreSQL, but when i try to login a user, fails with this error:
```
ValueError > Invalid salt in LoginController on line 52
```
and line 52 have:
```
if auth.login(request.input('name'), request.input('password')):
```

**To Reproduce**
1. Create a project using PostgreSQL database
2. Seed users to database
3. Try to login one

**Expected behavior**
I expect to login to the site

**Desktop (please complete the following information):**
 - OS: Debian Sid

**Additional context**
- PostgreSQL version: 12.1-1
- Masonite version: masonite-2.2.31
- Python version: 3.7.6

**Comment by josephmancuso** [comment]
cannot reproduce. This works fine for me 🤔
