### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by holic-cl** [MasoniteFramework/masonite#228]
**Describe the bug**
Tried to create new project inside of my HOME tmp folder, but create a project fails with:
```                                                                                      
  [NotADirectoryError]                                                                                        
  [Errno 20] Not a directory: '/home/user/tmp/MasoniteFramework-masonite-ad8aedd' -> '/home/user/tmp/test' 
```

**To Reproduce**
1. Go to `$HOME/tmp` folder
2. `craft new test`
3. See error

**Expected behavior**
A new project created

**Desktop (please complete the following information):**
 - OS: Debian Sid

**Additional context**
Craft Version: 2.1.2

**Comment by josephmancuso** [comment]
are you sure you have the correct permissions to create things in that folder?

**Comment by holic-cl** [comment]
Ohh, bad me, is a collapse with a filename in same folder
