### ISSUE TITLE
Module not found: Error: Can't resolve './bootstrap'

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#234]
**Describe the bug**
The `bootstrap.js` file is missing when using `react` and `vue` presets. This file: https://github.com/MasoniteFramework/masonite/blob/2.3/src/masonite/commands/presets/vue-stubs/app.js#L7

**To Reproduce**
```
craft preset react
npm install & npm run dev
```

**Comment by lazyguru** [comment]
Not sure how that got missed.  I can do a PR for it sometime later today or tomorrow (unless someone gets to it first)
