### ISSUE TITLE
Confirmation prompt for craft migrate in production

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#238]
**Is your feature request related to a problem? Please describe.**
When I run a migration on production, I want to be sure what it's going on. The confirmation prompt will be useful.

**Describe the solution you'd like**
An confirmation prompt when running `craft migrate` with `APP_ENV=production`. Adding a `--force` flag to force the commands to run without a prompt.

**Comment by josephmancuso** [comment]
This would be a breaking change if anyone has any production scripts so setting that label on this

**Comment by girardinsamuel** [comment]
Maybe it would be great to add a way to do a dry run just to check what is going to be migrated. 
This could be added in the confirmation prompt.
I can work on that ;)

**Comment by josephmancuso** [comment]
if you want to see what is being migrated you would run `craft migrate:status` that will show you what has migrated and what hasn't

**Comment by girardinsamuel** [comment]
Okay so no need to implement that then.

I am just going to add initial request which is:
- checking if env is production in migrate command, if yes display a confirmation prompt
- add a flag `--force` to migration command to force migration to be used in CI or script

**Comment by josephmancuso** [comment]
@girardinsamuel yes that's fine. notice the "Next Major Only" tag though. which means it needs to be based off of the develop branch. But since this is a migration change, the migrations in 3.0 will be for Masonite ORM. So the change needs to be done in the ORM repo

**Comment by girardinsamuel** [comment]
Okay, thanks for the info.

@josephmancuso  Also is there a convention for environment checking ? I mean that we can check `APP_ENV` value to be equal to `production` but there is no "production" flag so I am not sure if it's okay to just do that ?

**Comment by josephmancuso** [comment]
The check should just be something like:

```python
import os

if os.getenv('production'):
   # Halt the migration and ask for confirmation
```

**Comment by girardinsamuel** [comment]
Yeah sure !

I was just wondering if in Masonite, "production" name was enforced for production environment. What if someone on its production server has a file named .env.prod and then APP_ENV=prod.
But that's not a big deal (just curious !)😄

**Comment by josephmancuso** [comment]
oh, no its not enforced but it will be in the docs so it will be "the way to do things"

**Comment by girardinsamuel** [comment]
@josephmancuso Should we close this issue now or wait for next release of Masonite with ORM ?
