### ISSUE TITLE
Can't use craft with `strict=True, override=False` on service container

### ISSUE THREAD

**Issue by holic-cl** [MasoniteFramework/masonite#243]
**Describe the bug**
I tried to use `container = App(strict=True, override=False)` in my `wsgi.py` file but when i tried to use that options `craft` command won't works.

**To Reproduce**
1. Create a new empty project with masonite 2.3
2. modify `wsgi.py` file on line 13:
From:
`container = App()`
To:
`container = App(strict=True, override=False)`
3. Try to use `craft` command

**Expected behavior**
Craft command working

**Desktop (please complete the following information):**
 - OS: Debian unstable
 - Browser: Firefox Developer
 - Version: 74.0b1 (64-bit)

**Additional context**
This is the error message:
```
masonite.exceptions.StrictContainerException: You cannot override a key inside a strict container
```

**Comment by josephmancuso** [comment]
Strict willl be removed in 3.0 so closing this issue
