### ISSUE TITLE
Login returns exception: "Invalid salt" migrating from mariadb/mysql to postgresql

### ISSUE THREAD

**Issue by holic-cl** [MasoniteFramework/masonite#246]
**Describe the bug**
Login returns exception: "Invalid salt" migrating from mariadb/mysql to postgresql. Seems to be an not expected behavior on MariaDB/MySQL:
Masonite is saving the password in bytes. In MySQL it saves the password as a string in the database, in PostgreSQL it saves the password (correctly) as bytes since it is bytes.

To fix needs a check to prevent bytes from being encoded again in bytes:
https://github.com/MasoniteFramework/masonite/blob/2.3/src/masonite/auth/guards/WebGuard.py#L74

**To Reproduce**
1. Use MariaDB/MySQL
2. Do a login
3. Then migrate same DB to PostgreSQL
4. Do a login and see the error

**Expected behavior**
To make a normal login

**Desktop (please complete the following information):**
 * OS: Debian Sid
 * PostgreSQL 11.7 (Debian 11.7-0+deb10u1)
 * MariaDB 10.3.22-0+deb10u1
 * Masonite 2.3.2

**Comment by josephmancuso** [comment]
couldn't actually reproduce this but that change you made should fix it

**Comment by holic-cl** [comment]
Hi, i found the problem, i was saving the user password in this way:
```
password = bcrypt.hashpw(
    password.encode(encoding='UTF-8', errors='strict'),
    bcrypt.gensalt()
)
data = {'name': "user", 'email': "email@example.com", 'password': password}
User.create(data)
```

To fix this issue i had to decode the password before save the new user
```
data = {'name': "user", 'email': "email@example.com", 'password': password.decode('utf-8')}
User.create(data)
```
