### ISSUE TITLE
Add Masonite to official "WebFrameworks - Python Wiki"

### ISSUE THREAD

**Issue by matthewlenz** [MasoniteFramework/masonite#249]
I notice that Masonite isn't mentioned on the official python web frameworks wiki page.  Is that intentional? https://wiki.python.org/moin/WebFrameworks

**Comment by girardinsamuel** [comment]
I have requested the editing rights for this page. Once I have those, I will add it to the wiki !

**Comment by girardinsamuel** [comment]
And here we go : https://wiki.python.org/moin/WebFrameworks 🚀🥳
