### ISSUE TITLE
Cli commands doesn't create files like CamelCase pattern

### ISSUE THREAD

**Issue by marcuxyz** [MasoniteFramework/masonite#250]
**Is your feature request related to a problem? Please describe.**
When, we try create a new controller, model and others features file through the cli. It doesn't create the file with Camelcase patterns.

**Describe the solution you'd like**
Maybe, get output and convert using .title() function

- [ ] Is this a breaking change?
No

**Comment by josephmancuso** [comment]
I think you mean PascalCase?

**Comment by marcuxyz** [comment]
Yes, you're right!

**Comment by josephmancuso** [comment]
@marcuxyz can you give me an example of a command input that does not make a PascalCase file? are you doing something like 

```
$ craft model company_settings
```

?
