### ISSUE TITLE
Craft tinker classes aliases

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#251]
**Is your feature request related to a problem? Please describe.**
Typing `from app.User import User` or other fully qualified classname by hand can be quite annoying.

**What do we currently have to do now?** 
Automatically registers Model aliases;

```
>>> User.where('email', 'example@example.com')
# Automatically import app.User model
```

**Comment by josephmancuso** [comment]
love this idea. Could be pretty simple using the autoload class. That class is a bit of an internal thing so I'm not sure if I wrote docs for it

**Comment by girardinsamuel** [comment]
That would be really nice.
In Django, an external packages `django-extensions` to add all coold stuff contains a command `shell_plus` that I often use which role is to autoload all models (autoload settings & conventions can be defined as well as additional directory loading).
https://django-extensions.readthedocs.io/en/latest/shell_plus.html

But all can be covered easily with `AUTOLOAD` settings in config I guess, so yes adding this would be really cool 🚀.

**Comment by girardinsamuel** [comment]
This will be done in next major release (M4).
