### ISSUE TITLE
Testing: assertViewIs assertion

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#257]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could assert the name of the view that is returned.
```python
self.assertTrue(self.get('/login').assertViewIs('auth.login'))
```

**Comment by josephmancuso** [comment]
Technically speaking the `assertX` methods always return self so it would also be true. The correct syntax would be:

```python
self.get('/login').assertViewIs('auth.login')
```

**Comment by girardinsamuel** [comment]
Already implemented as `assertIsNamed()`.
```python
self.get('/login').assertIsNamed('auth.login')
```
