### ISSUE TITLE
Testing: assertRedirectTo Assertion

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#258]
**Is your feature request related to a problem? Please describe.**

```python
response = self.post('/login', {
       'email': 'user@example.com',
       'name': 'Joe',
       'password': 'secret'
})

response.assertRedirectTo('home') # route name, URI or Controller+method
```

**Comment by girardinsamuel** [comment]
For now it's possible to do `self.assertRedirect("/dashboard")` passing the redirect URI.
This won't be integrated into M3 but in M4, redirections assertions will be able to test URI and view name 😉.
