### ISSUE TITLE
Missing validation error messages due to time offset

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#259]
I used the `craft auth` command to create the standard auth controllers, templates, and routes. When testing it, the error messages never appeared. A hint in the documentation about session messages disappearing after 2 minutes led me to suspect that the messages were not appearing due to the time offset.

**To Reproduce**
1. Set the clock on the client computer 3 minutes after the server time.
2. Run `craft serve`
3. Go to localhost:8000/login
4. Enter "guest" in the email address
5. Do not enter a password
6. Click Login

**Expected behavior**
You should see a message that the password is required and that the email must be a valid email address. (See the auth.LoginController.py for the messages)

**Actual error**
The messages do not appear at all. You get the same login form as before. It seems that the cookies are considered expired before they are set, and therefore omitted. Once the time of the client is corrected, the errors appear as expected. The lack of errors is quite confusing to users.

**Desktop Client:**
 - MacOS
 - Safari
 - Version 12.1

**Comment by josephmancuso** [comment]
moving to the main masonite repo

**Comment by josephmancuso** [comment]
> Set the clock on the client computer 3 minutes after the server time.

How do you do this? and why is the computer time different than what Python will pick up?

**Comment by josephmancuso** [comment]
are you starting Masonite and then changing the computers time?

**Comment by tpow** [comment]
For whatever reason the server time and client desktop time were slightly off. In this case, you just set the current system date and time on the client computer. This only affects the Masonite frame due to how it is setting the cookies. I'm not sure why it needs to have such as quick expiration time.

**Comment by josephmancuso** [comment]
the goal is to only see the messages and deal with them once. I didn't want to refresh the page and still see the same error messages

**Comment by josephmancuso** [comment]
The session is stored in a cookie for 2 seconds. Its possible the response is taking longer than 2 seconds and the cookies get deleted?

**Comment by josephmancuso** [comment]
I just don't know if this is a Masonite issue or because your client's time is messed up

**Comment by tpow** [comment]
I would consider it a Masonite issue. Having clock offsets of a few minutes between client and server would not be uncommon. To have this cause missing error messages is unexpected and causes usability problems.

**Comment by josephmancuso** [comment]
right. We can't flash a message for a few minutes. The point of a flash is to show it once when redirecting to the previous page and then disappear when you refresh the page. I can extend it out a couple more seconds but that won't fix the issue. 

I'll take a look since the cookie should be saved on the client side anyway so the server time shouldn't matter. Might be an issue but for a different reason.

I'll do some testing

**Comment by tpow** [comment]
This routinely fails for me in Safari when the client and server times are out of sync, which is frustrating and happens often. I removed the "expires='2 seconds'" from /masonite/drivers/session/SessionCookieDriver.py and all the validation messages appear (but obviously don't disappear). I believe using a cookie expiration for this is misguided because it provides inconsistent behavior.

I have never had flashed messages fail to display in Flask (even with the same client-server setup-I just tried), so I wondered about its more reliable mechanism. The Flask framework uses the act of retrieving the flashed messages for display in a view as the trigger for the messages to be removed (from the session). If you are interested, see "get_flashed_messages" https://github.com/pallets/flask/blob/master/src/flask/helpers.py#L414
Flask can do this because the function is available as a view helper with access to the context. 

This is a bit different than Masonite's MessageBag, but something similar could be done.

**Comment by josephmancuso** [comment]
Ok let me take another look at this tonight

**Comment by josephmancuso** [comment]
@tpow This should be fixed in #310 

Can you confirm this works for you?

You can test this by doing these 2 things:

1) Uninstall masonite an install this new version:
```python
pip uninstall masonite && pip install https://github.com/masoniteframework/masonite/archive/fix/259.zip
```

2) Add a config option to the `config/session.py`:

```python
DRIVER = env('SESSION_DRIVER', 'cookie')

# Here
DRIVERS = {
    'cookie': {
        'flash_expires': '1 minute' # This is now setting the flash cookie time. Can set this to 1 hour if you want.
    }
}
```

Once done you can now use a slightly different syntax for getting and resetting the flash info similiar to flask:

```html
{% if bag().any() %}
    {% for message in session().get_error_messages() %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
```

The `session().get_error_messages()` gets and also resets flash info.

Can you test this for me and confirm it works the way you need it to?

**Comment by tpow** [comment]
@josephmancuso Thanks for taking a look at this!

I tested the fix and confirmed that it corrects the problem. Thanks! (Because I was testing the fix in the standard auth/login template, I needed to change the get_error_messages line to "for error in" instead of "for message in", but it works as expected.)

After reviewing your change, I went back and removed the DRIVERS modifications in step 2, and also removed the expires line in the flash function in drivers/session/SessionCookieDriver.py. It looks like this now (no expiration is set):

```
self.request.cookie('f_{0}'.format(key), value) 
# removed -> expires=config('session.drivers.cookie.flash_expires', '2 seconds'))
```

I restarted everything and it works exactly the same as your bug fix (reliably). I remain puzzled what the cookie expiration is trying to accomplish. All it does is make the flash unreliable based on the server/client time offsets. If the offset had been more than 1 minute (which is quite possible--you'd be surprised how many computers get set to the correct time but wrong timezone which has a similar effect) I would need to tune the expiration to much longer. I do not see the advantage.

I am not as concerned about my own code as I am about the other masonite sites that users may encounter that inexplicably won't provide informative messages because of this bug. I would recommend eliminating the expiration on the cookie and either using and recommending the new mechanism (such as in craft auth) or better retrofitting it so the message bag "API" stays the same but uses the new mechanism.

**Comment by josephmancuso** [comment]
This is merged now. Flashing data is a bit complicated because there is no built in support like PHP has with sessions. The trick to flashing is to only have the data available for a certain amount of time. I don't see any further issues with this especially since we can now modify session expiration time on a per application basis. I'll consider this closed for now as I don't think there should be any further work on this
