### ISSUE TITLE
The smtp mail driver should support optional authentication

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#260]
I am trying to set up the mail driver to connect to a local SMTP server. Using the python smtplib module, this is as simple as `s = smtplib.SMTP('localhost')`.

The default port for smtp is 25, so I can add that to the .env file like this:

```
MAIL_DRIVER=smtp                                                                 
...                                                  
MAIL_HOST=localhost                                                              
MAIL_PORT=25 
```

However, there isn't a way to have the smtp mail driver skip the login step in MailSmtpDriver.py in send. It'd be nice to add a configuration option to make it options. It could add support for this in .env like MAIL_LOGIN_REQUIRED=True, update config/mail.py to support it, and use it in MailSmtpDriver:

```
if config.get('login_required'):
    self.smtp.login(config['username'], config['password']) 
```

Do I currently need to create a new mail driver just to be able to skip the login step?

As an aside, it appears that there's also undocumented support for an "ssl" option in the smtp mail driver. It would be nice to add that to config/mail.py as well, ideally with support for setting it in .env using MAIL_SSL=True.

**Comment by josephmancuso** [comment]
the docs for ssl are here https://docs.masoniteproject.com/useful-features/mail#ssl-optional

You can deff open a PR. I hadn't thought of the use case where there is no username and password for localhost mail servers. A simple IF statement works like you have here

https://github.com/MasoniteFramework/masonite/blob/b4239f92ae91a8ad1ec45dc6efcd11a1cabbbc5e/src/masonite/drivers/mail/MailSmtpDriver.py#L46

**Comment by josephmancuso** [comment]
Similiar to how we have the SSL it would be easy if we just had:

```python
DRIVERS = {
    'smtp': {
        'host': os.getenv('MAIL_HOST', 'smtp.mailtrap.io'),
        'port': os.getenv('MAIL_PORT', '465'),
        'username': os.getenv('MAIL_USERNAME', 'username'),
        'password': os.getenv('MAIL_PASSWORD', 'password'),
        'ssl': True,
        'login': False
    },
```

**Comment by tpow** [comment]
Closing because the fix for this has been merged.
