### ISSUE TITLE
Remove storage/logs from git tracking

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#261]
**Is your feature request related to a problem? Please describe.**
You have all your application's logs into your cvs.

**What do we currently have to do now?** 
Adding a `.gitignore` file into `storage/logs` with this content:
```
*
!.gitignore
```

**Comment by Rohithgilla12** [comment]
Can I take it up?

**Comment by josephmancuso** [comment]
@Rohithgilla12 sure :)

**Comment by Rohithgilla12** [comment]
I guess this is already implemented, I just checked it here.
https://github.com/MasoniteFramework/masonite/blob/2.3/storage/logs/.gitignore
