### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#264]
It looks like Masonite has been restructured and that 2.3 and future development work is done in the main masonite repository. Correct me if I am misunderstanding.

The readme file has TWO Contributing sections. The second one, immediately above the Contributors section says "Development will be on the current releasing branch of the Core Repository (typically the develop branch) so check open issues, the current Milestone and the releases in that repository." Is this incorrect for 2.3 and future development?

Thanks for clarifying. It would be helpful to consolidate the two Contributing sections in the readme.

**Comment by josephmancuso** [comment]
yes it is now in this repository. Can you update that section if you have time? https://github.com/MasoniteFramework/docs

I've been a bit busy recently

**Comment by josephmancuso** [comment]
the core repo (masoniteframework/core) was the old repository but 2.3+ development has moved to this one. This repo used to only contain the project shell
