### ISSUE TITLE
fix the working of codecov

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/masonite#267]

**Comment by girardinsamuel** [comment]
Hi there !

I can see coverage badge on repo README. What is not working here ? Could you add some details ?

Thank you very much !

**Comment by girardinsamuel** [comment]
I can work on that if still needed, can someone give details about the issue ?

Thanks 👍

**Comment by victoraguilarc** [comment]
is it resoved? is there an PR? I can work on it

**Comment by josephmancuso** [comment]
@victoraguilarc no I don't believe it fixed.
