### ISSUE TITLE
craft key should put generated key to .env file

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#268]
**Is your feature request related to a problem? Please describe.**
`craft key` should put generated key to `.env` file.

**Comment by josephmancuso** [comment]
`craft key --store` does this. Should we make that the default behavior and have something like `craft key --no-store`?

**Comment by nioperas06** [comment]
Yes, making this default is better I think.

**Comment by simphiwehlabisa** [comment]
@josephmancuso yep i think that would be a great enhancement

**Comment by josephmancuso** [comment]
This is in develop branch so closing. Will be available in 3.0
