### ISSUE TITLE
Resend verification email issue - cryptography.fernet.InvalidToken

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#269]
**Describe the bug**

I generated new Masonite app and `craft auth`:

![Screenshot from 2020-03-24 16-53-34](https://user-images.githubusercontent.com/11293401/77447607-26473180-6df0-11ea-9e79-88efa7bb5a6e.png)

When I clicked on "Click here", URL `email/verify/send`, I have this as error:

![Screenshot from 2020-03-24 16-58-08](https://user-images.githubusercontent.com/11293401/77448067-b2f1ef80-6df0-11ea-98ed-184393e9f20c.png)

**Comment by girardinsamuel** [comment]
Hello @nioperas06 ✋ 
Do you still get this issue ? I have tested on a local project, and it's working !

**Comment by nioperas06** [comment]
Hi @girardinsamuel I just tried again in a new project with Masonite `2.3.17`. Same issue. Maybe I'm doing something wrong 🤔 

Reproduction:
- Create a new Masonite project.
- Run: craft auth
- Create a new route and add `verified` middleware. Ex: `Get("/home", "auth.HomeController@show").name("home").middleware('verified', )`
- Reach the new route protected by the middleware.
- Click on "Click here" to try to resend the email.

**Comment by girardinsamuel** [comment]
Oh okay, actually I got it working when registering, I received an email and click on it to confirm my email.
But I did not try to add the middleware to another route, and here I got the same error ! 

I'll have a look this week ;)

**Comment by josephmancuso** [comment]
@girardinsamuel Thanks Samuel!

**Comment by josephmancuso** [comment]
Fixed. Will be available in next release
