### ISSUE TITLE
The craft command does not create the project directory

### ISSUE THREAD

**Issue by ChafikHadjAbdouRazack** [MasoniteFramework/masonite#270]
**Describe the bug**
Hi! I'm trying to create some project with command craft new project_name , but after command execution the project is created outside the directory supplied as project name  and the project directory isn't created.

**To Reproduce**
1. Open terminal
2. Move to some directory
3. Execute craft new project_name
4. After command execution all masonite project files is outside of the project directory supplied as craft command parameter and also the project directory isn't created

**Expected behavior**
The craft command may create directory of the project

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4
- Python 3.8.2

**Comment by josephmancuso** [comment]
the `project_name` is just the project name. You need to add another argument for the directory location. like:

```
craft new project_name target_directory
```

this behavior might change in the future. Looking back on it its a little outdatted with the recent Masonite 2.3 change of a simple `craft new`.

**Comment by josephmancuso** [comment]
either way this was broke so I made a fix on 2.3.4. Please update 👍
