### ISSUE TITLE
[FR] An easy way to disable StackOverflowIntegration

### ISSUE THREAD

**Issue by lokielse** [MasoniteFramework/masonite#271]
**Is your feature request related to a problem? Please describe.**
- Exception page display showly due to network requests in `StackOverflowIntegration`
- SSL issue of `requests` due to self-signed  certificates, User can't pass `verify=False`

https://github.com/MasoniteFramework/masonite/blob/d2a813ef55967de3838a8857f082e39dfe48bf61/src/masonite/exception_handler.py#L97-L103

**What do we currently have to do now?** 
- Add some option to disable some features of exception_handler

**Describe the solution you'd like**
- Add some option to disable some features of exception_handler

**Describe alternatives you've considered**
- Integrations array is configurable

- [ ] Is this a breaking change?

**Comment by josephmancuso** [comment]
this is actually fixed. It's now wrapped around a try catch
