### ISSUE TITLE
Hi pro, how to upload file from url

### ISSUE THREAD

**Issue by sanandanguyen** [MasoniteFramework/masonite#272]
Hi pro, how to upload file from url

I using 'upload.driver('disk').store(open('some/file.txt'))' but this only process on local.
Please help me.

Thanks all

**Comment by Marlysson** [comment]
We have the slack to post some doubts related to some use cases: https://masoniteproject.slack.com/

But what do you mean "upload file from url" ?

**Comment by nioperas06** [comment]
Assuming that your file is not submitted by a form, you'll have to send a request to the URL (using something like `urllib2.urlopen`) to retrieve the file.
