### ISSUE TITLE
Is public folder used? Which style.css?

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#276]
I'm trying to determine if the public folder is obsolete in Masonite 2.3.4 or confusingly named. I'm also trying to determine which style.css is appropriate to change to update my project. I think the public folder can be eliminated, but wanted to check. I also don't know where this folder comes from because I don't see it in this branch, but I may have missed it.

**To Reproduce**
1. Follow the instructions in the documentation https://docs.masoniteproject.com:
2. Install masonite (venv, pip, etc.)
3. Craft new

Examine the folders that craft has built. The public folder has css and js folders. In typical web frameworks the public folder is used for static files that are used by the project.

However, it appears that the templates created are referencing /static/ for the style.css. According to /config/storage.py this is a reference to /storage/static, /storage/compiled, and storage/uploads.

In the template, it refers to /static/style.css. This seems to be found in /storage/compiled/style.css (possibly previously built from /storage/statics/sass/style.scss). The style.css in /public/css is similar. I think the one is compiled is the only one that matters. If I understand correctly 2.3 eliminated any scss compilation, so unless I want to set up webpack and use a compilation pipeline, I can just change this css directly.

**Comment by josephmancuso** [comment]
Hey sorry for late reply. The public folder actually comes from @nioperas06 tutorial on adding Laravel Mix. I personally don't use it. If you don't need it feel free to delete it. I put all static assets and compiled assets in storage directory
