### ISSUE TITLE
Preset command didn't found the bootstrap.js file

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/masonite#277]
**Describe the bug**
When run the preset command in a new project using some of the predefined presets the **bootstrap.js** isn't found.

**To Reproduce**
1. Create a new project
2. Run the command **craft preset vue**

**Expected behavior**
The successful installation of frontend files

**Error**
```[Errno 2] No such file or directory: 'd:\\projetos\\venvs\\masonite\\lib\\site-packages\\masonite\\commands\\presets/shared-stubs/bootstrap.js```

**Desktop (please complete the following information):**
System Information         Windows AMD64 32bit
Python Version                CPython 3.6.4
Virtual Environment        ✓
Masonite Version            2.3.4
Craft Version                   2.3.4

**Additional context**
The version that came from github haven't the **shared-folder** and so **bootstrap-stubs** ( but without the js file )

**Comment by lazyguru** [comment]
I was able to reproduce this on a clean install of 2.3

```
Environment Information
-------------------------  ------------------
System Information         MacOS x86_64 64bit
System Memory              16 GB
Python Version             CPython 3.8.0
Virtual Environment        ✓
Masonite Version           2.3.4
Craft Version              2.3.4
APP_ENV                    local
APP_DEBUG                  True
```

```
craft preset react
Scaffolding Application ...


  [FileNotFoundError]
  [Errno 2] No such file or directory: '<redacted>/ve
  nv/lib/python3.8/site-packages/masonite/commands/presets/shared-stubs/bootst
  rap.js'


preset <name>
```

**Comment by lazyguru** [comment]
It looks like the `shared-stubs` directory is missing:
```
ls venv/lib/python3.8/site-packages/masonite/commands/presets
Bootstrap.py    Remove.py       __pycache__     remove-stubs
Preset.py       Vue.py          bootstrap-stubs vue-stubs
React.py        __init__.py     react-stubs
```

**Comment by lazyguru** [comment]
The directory is definitely there on the tag, so this must be a packaging issue? https://github.com/MasoniteFramework/masonite/tree/v2.3.4/src/masonite/commands/presets/shared-stubs

**Comment by Marlysson** [comment]
@lazyguru 
I think lack of more one file to be packaging again:

When I ran the "npm install && npm run dev" the following message appears:

```
ENOENT: no such file or directory, open 'D:\Projetos\trackwork\package.json'
```

I think the package.json isn't copied when the preset is installed, right?

**Comment by lazyguru** [comment]
Just copying answer here so if someone runs across this in the future they will have context:

package.json isn't copied as part of the preset command. It is added to the project when you run `craft new`. If you upgrade from an older version of Masonite, you might not have a package.json. You can copy it from here: https://github.com/MasoniteFramework/masonite/blob/v2.3.5/package.json

NOTE: It is not recommended to run the "preset" commands on an existing project as it will overwrite files without warning you
