### ISSUE TITLE
Echoing multiples values

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#284]
**Is your feature request related to a problem? Please describe.**
It would be useful to write something like this: `dd(1, 'test', [])`.

**Comment by tpow** [comment]
I'm going to take a stab at adding this. I have wanted this frequently and have a pretty good idea how to add it.

**Comment by tpow** [comment]
I added support for this in #315.

**Comment by josephmancuso** [comment]
This is done and merged
