### ISSUE TITLE
Fresh Install - Date field format error

### ISSUE THREAD

**Issue by sn0rcha** [MasoniteFramework/masonite#288]
**Describe the bug**
Getting a serialization error on a fresh install when serializing a model with timestamp fields. Additionally, the ```get_date_format``` function returns 'DD-MM-YY' instead of the formatted date when using 

```
__dates__ = ['created_at']

def get_date_format(self):
        return 'DD-MM-YY'
```
Using the following instead works:

```
def get_date_format(self):
        return '%d-%m-%Y'
```

**To Reproduce**
1. Add a Model with timestamps
2. Return model from a controller eg - User.find(1)
3. Set date format 

**Expected behavior**
Non-serialization errors for default timestamp fields and date format correctly applied.

**Comment by josephmancuso** [comment]
can you put the error here?

**Comment by josephmancuso** [comment]
specifically the stack trace

**Comment by sn0rcha** [comment]
Sorry, it was my date field I didn't flag as a date field in the model that was throwing an error.

Below is the output from query:  ```Asic.select('id','updated_at','date_of_expiry')```

```{"id": 67, "updated_at": "DD/MM/YYYY", "date_of_expiry": "DD/MM/YYYY"}```

Using: 

```
from config.database import Model


class Asic(Model):
    """Asic Model."""
    __dates__ = ['date_of_expiry']

    def get_date_format(self):
        return 'DD/MM/YYYY'

    pass
```

Also, is there a way to specify a different format for date fields vs date time fields?

**Comment by josephmancuso** [comment]
> Also, is there a way to specify a different format for date fields vs date time fields?

You can try using an acessor to change the date format

https://orator-orm.com/docs/0.9/orm.html#accessors-mutators

**Comment by sn0rcha** [comment]
Thanks Joseph. Any idea why it would return 'DD/MM/YYYY' instead of the formatted date? - Is it a change in library from arrow to pendulum? - https://orator-orm.com/docs/0.9/orm.html#date-mutators

**Comment by josephmancuso** [comment]
yeah it could be. I didn't build orator so its hard to give trouble shooting guides to it. We are building our own ORM so once that becomes default ORM I should be able to provide much better support since itll be first party

**Comment by josephmancuso** [comment]
Its here if you want to take a look. It will initially be a drop in replacement of Orator for the most part. Possibly a few tweaks https://github.com/MasoniteFramework/orm****

**Comment by sn0rcha** [comment]
thanks for your help.
