### ISSUE TITLE
StaticFiles returning 404 Error

### ISSUE THREAD

**Issue by darryllin** [MasoniteFramework/masonite#289]
I maintained the STATICFILES config as per screenshot below
![Screenshot_20200510-011240](https://user-images.githubusercontent.com/65080146/81477517-7ae92380-925b-11ea-895d-f7ed431a9b3f.png)

My CSS and JS files are already stored in the corresponding directories. 

However my site is not rendering correctly due to 404 error on static files. I am also having issues when testing it in the original configuration before. I have also restarted nginx and uwsgi gracefully, but still no luck. 

I am on nginx 1.14.0, running python3.6 on uwsgi.

Any pointers to where I should be looking at?

**Comment by josephmancuso** [comment]
It renders correctly when using it locally right? Like during development? Or are you trying to use nginx for development?

**Comment by Marlysson** [comment]
Do you tried to put in alias different names? Like:

```
'storage/assets/js/' : 'assets/js',
'storage/assets/css/' : 'assets/css'
```

**Comment by josephmancuso** [comment]
Also what is your uwsgi command you are running? There’s a few possibilities of the issue but I’ll need some more context

**Comment by darryllin** [comment]
Hey Joseph - thanks for your good work bringing on Masonite.

I'm using nginx/uwsgi as my development server.

Here is my ini file:
chdir           = /var/www/abc/project
module          = wsgi:app
home            = /var/www/abc/venv
master          = true
processes       = 4
threads		= 2
socket          = /tmp/abc.sock
stats		= 127.0.0.1:8090
chmod-socket    = 660
vacuum          = true
logger		= file:/var/www/abc/logs/error.log
touch-reload	= /var/www/abc/project.ini

I have also tried Marlysson's suggestion. This is how I'm referencing my static files in my html:
<link rel="stylesheet" href="/assets/bootstrap.min.css">

I have also tried:
<link rel="stylesheet" href="/assets/css/bootstrap.min.css">

Hope that helps and thank you all.

**Comment by josephmancuso** [comment]
@darryllin try changing:

```
module = wsgi:app
```

to 

```
module = wsgi:application
```

that should actually fix it
```

**Comment by darryllin** [comment]
You're a champ, Joseph. Thanks for your guidance on this.

**Comment by josephmancuso** [comment]
💪 The reason for this for anyone who finds this later is that `application` is the actual entry point for the wsgi app. `app` is the container really. So when you use `wsgi:app` you don't get to the point where Whitenoise is bound yet.

**Comment by darryllin** [comment]
👍
