### ISSUE TITLE
[ConnectionError]   HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Maso   niteFramework/cookie-cutter/releases (Caused by NewConnectionError('<urllib3.connection.HTTPSCon   nection object at 0x1080e2ba8>: Failed to establish a new connection: [Errno 61] Connection refu   sed'))

### ISSUE THREAD

**Issue by Abeautifulsnow** [MasoniteFramework/masonite#290]
when I want to run `craft new` command to create a new project... But i get a error info as follow:
```
[ConnectionError]
  HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Maso
  niteFramework/cookie-cutter/releases (Caused by NewConnectionError('<urllib3.connection.HTTPSCon
  nection object at 0x1080e2ba8>: Failed to establish a new connection: [Errno 61] Connection refu
  sed'))
```
I attempt to search Google for this error message, while do not get a solution, so can someone suggest me how to get rid of this error?

**Comment by josephmancuso** [comment]
Can you tell me a little bit more about your environment?

**Comment by josephmancuso** [comment]
Are you behind a firewall, personal or corporate, do you use any vpns? Python version? Operating system? Virtual environment?

**Comment by Abeautifulsnow** [comment]
> Are you behind a firewall, personal or corporate, do you use any vpns? Python version? Operating system? Virtual environment?

@josephmancuso I use Mac OS catalina 10.15.3 and there is only a vpn plugin called Google Helper in my chrome browser. And the version of python is 3.7.3. So maybe it's a network problem(but i can access github website...)?

**Comment by josephmancuso** [comment]
hmmm. This is gonna be something I won't be able to replicate. 

Can you install the repo manually?

full install steps for this would be:

```
$ git clone https://github.com/masoniteframework/cookie-cutter
$ python -m venv venv
$ source venv/bin/activate
$ pip install masonite
$ craft install
```

**Comment by Abeautifulsnow** [comment]
> hmmm. This is gonna be something I won't be able to replicate.
> 
> Can you install the repo manually?
> 
> full install steps for this would be:
> 
> ```
> $ git clone https://github.com/masoniteframework/cookie-cutter
> $ python -m venv venv
> $ source venv/bin/activate
> $ pip install masonite
> $ craft install
> ```

hmmm...how weird is that. The `craft new` command is OK now😂. . . Maybe it's a network problem, maybe it's another problem. . .In addition, the manual installation method is also useful to me... Thanks very very much...
