### ISSUE TITLE
How to customize the response

### ISSUE THREAD

**Issue by polichan** [MasoniteFramework/masonite#291]
First, thanks for this great framework you guys made.
----
Here is my issue content: 
Currently, the response when returning a Model in the Controller is:
```json
[
  {
   "id": 1,
   "name": "1",
   "created_at": "2020-05-14T17:11:11.481139",
   "updated_at": "2020-05-14T17:11:11.481139"
  }
]
```
Sometimes, we need to carry some other informations in response. For example: 
```json
{
 "code": 200,
 "message": "success",
 "data": [
  "data should be here"
 ]
}
```
Any ideas to implement? It seems the data variable will be grabbed from the Service Container and return to the WSGI server. Can we extend the `Response` class and override the method in order to achieve this goal ? I'll be very grateful to you if you can give me some tips.

```python
return iter([container.make('Response')])
```

**Comment by Marlysson** [comment]
@polichan Did you solve this issue? Can you share how you did?
