### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by jmsfrancies** [MasoniteFramework/masonite#292]
**Describe the bug**
I have the latest openssl, python 3.6.5, and I am using masonite 2.3. I am using pipenv for my virtual environment. The craft command works like a charm with creating the project, but when I run the "craft serve" command. I receive the command "serve is not defined" error.

**Image**
![Image 5-16-20 at 4 14 PM](https://user-images.githubusercontent.com/35373311/82130364-5c6db580-9790-11ea-8a51-7e6248259028.jpeg)

** OS **
I am using the MacOS 10.15.4

**Comment by josephmancuso** [comment]
Could you run `python craft` and see if you get any errors?

**Comment by jmsfrancies** [comment]
<img width="1160" alt="Screen Shot 2020-05-18 at 7 34 56 AM" src="https://user-images.githubusercontent.com/35373311/82213613-158bd700-98da-11ea-95c7-e1d05cfff683.png">

**Comment by josephmancuso** [comment]
can you tell me the exact steps you are doing to reproduce? seems like its trying to install a previous version of masonite 🤔

**Comment by jmsfrancies** [comment]
1) I go to the file directory.
2) I install pipenv within the project directory.
3) I write the command "pipenv install masonite" and "pipenv install masonite --dev".
4) I write the command "craft new tutorial ." and the command "craft install" .
5) Finally, I attempt the command  "craft serve".

<img width="1160" alt="Screen Shot 2020-05-18 at 7 41 37 AM" src="https://user-images.githubusercontent.com/35373311/82214165-035e6880-98db-11ea-90f7-c421386dfc62.png">

**Comment by jmsfrancies** [comment]
I attempted to download pip3 install gevent_openssl and I had this error.

<img width="638" alt="Screen Shot 2020-05-18 at 7 47 35 AM" src="https://user-images.githubusercontent.com/35373311/82214693-d9597600-98db-11ea-8488-7f9d58093144.png">

**Comment by jmsfrancies** [comment]
When I attempted to install cryptography 2.7 within the project. This error occurred within my virtual environment.

<img width="1160" alt="Screen Shot 2020-05-18 at 7 52 24 AM" src="https://user-images.githubusercontent.com/35373311/82215134-86cc8980-98dc-11ea-93f4-e28e3286faa4.png">

**Comment by josephmancuso** [comment]
Firstly the latest version is 2.3.7 but for some reason your system is trying to install 2.3.6 .. 🤔

**Comment by josephmancuso** [comment]
2.3.7 has the fix for the cryptography issues

**Comment by josephmancuso** [comment]
also with your flow you miss installing the requirements in the requirements.txt file after you run craft new. After craft new you'll also have to run:

```
$ pipenv install -r requirements.txt
```

**Comment by josephmancuso** [comment]
You also have an even bigger issue in your second screenshot which says its installed 2.2.2 which is a super old version of Masonite. Installing that version would deff throw the authentication provider error.

Something a little wacky is going on with your install steps

**Comment by josephmancuso** [comment]
@jmsfrancies did you manage to get this fixed?

**Comment by jmsfrancies** [comment]
Yes I did! I managed to get the masonite commands to work by using virtualenv instead of pipenv. Thank you for your patience!
