### ISSUE TITLE
Routes not working 

### ISSUE THREAD

**Issue by toplinuxsir** [MasoniteFramework/masonite#296]
python3.8 masonite versin: 2.3.8
```
craft new blog
craft controller helloworld
```
change web.py 
```
ROUTES = [
    Get("/", "WelcomeController@show").name("welcome"),
    Get("/hello", "HelloWorldController@show"),
]
```

HelloWorldController.py 
```
class HelloWorldController(Controller):
    """HelloWorldController Controller Class."""

    def __init__(self, request: Request):
        """HelloWorldController Initializer

        Arguments:
            request {masonite.request.Request} -- The Masonite Request class.
        """
        self.request = request

    def show(self, view: View):
        print("run the controllers.....")

        return {"name": "Jason", "addr": "NY"}
```

craft serve

and acces http://127.0.0.1:8000/hello
Get 404 page 

and run 
```
craft show:routes
```
get empty list

**Comment by nok** [comment]
Hello @toplinuxsir , you are close, here is an working example:

```bash
craft new
craft controller HelloWorld
```

```python
# app/http/controllers/HelloWorldController.py

"""A HelloWorldController Module."""

from masonite.response import Response
from masonite.controllers import Controller

class HelloWorldController(Controller):
    """HelloWorldController Controller Class."""

    def show(self, response: Response):
        return response.json(dict(foo='bar'))  # <--- return a response of type json
```

```python
# routes/web.py

"""Web Routes."""

from masonite.routes import Get, Post

ROUTES = [
    Get('/', 'WelcomeController@show').name('welcome'),
    Get('/hello', 'HelloWorldController@show').name('hello'),
]
```

Show all routes:

```bash
craft show:routes

# ========  ======  =======  ========  ============
# Method    Path    Name     Domain    Middleware
# ========  ======  =======  ========  ============
# ['GET']   /       welcome
# ['GET']   /hello  hello
# ========  ======  =======  ========  ============
```

Start the application:

```bash
craft serve
```

Make request with `curl`:

```bash
curl 127.0.0.1:8000/hello

# {"foo": "bar"}
```

Make request with [httpie](https://httpie.org/):

```bash
http 127.0.0.1:8000/hello

# HTTP/1.1 200 OK
# Content-Length: 14
# Content-Type: application/json; charset=utf-8
# Date: Tue, 26 May 2020 07:19:16 GMT
# Server: WSGIServer/0.2 CPython/3.7.7
# Set-Cookie: csrf_token=83f1474db94cd8d786ad1d47cffcd8; HttpOnly;Path=/
# 
# {
#     "foo": "bar"
# }
```

**Comment by josephmancuso** [comment]
@nok Returning a dictionary should work as well. Both your code is the same.

@toplinuxsir Running through your examples works for me. a bigger issue is that there are no routes when you run `show:routes` .. could you provide me with any more information?

**Comment by josephmancuso** [comment]
@toplinuxsir are you sure you are in the correct virtual environment and the correct project directory?

**Comment by toplinuxsir** [comment]
@josephmancuso  Yes, I confirm ，right venv and right project directory
Attach is the full project 
[blog1.zip](https://github.com/MasoniteFramework/masonite/files/4687377/blog1.zip)

**Comment by nioperas06** [comment]
Created a new venv and installed the dependencies from `requirements.txt`, `craft show:routes`:

![Capture d’écran 2020-05-27 à 09 17 03](https://user-images.githubusercontent.com/11293401/82994983-e6bce180-9ffa-11ea-8344-d12bf373d9b0.png)

**Comment by josephmancuso** [comment]
![Screen Shot 2020-05-27 at 10 50 38 PM](https://user-images.githubusercontent.com/20172538/83092995-9a11ee80-a06c-11ea-9a8a-c018e8afa476.png)
![Screen Shot 2020-05-27 at 10 50 14 PM](https://user-images.githubusercontent.com/20172538/83092996-9a11ee80-a06c-11ea-8501-00b3cd70e183.png)

@toplinuxsir  this also works fine for me as well.

1) unzip your blog1 file then:

```
$ pip install -r requirements.txt
$ craft show:routes
```

I see the routes there fine.

what virtual environment are you using? conda? virtualenv?

You are using windows? mac?

**Comment by toplinuxsir** [comment]
@josephmancuso  Yes , I  user virtual environment  with virtulenv, I am using ubuntu linux 20.04
Thanks

I active the virtulenv , and  then pip install -r  ./requiements.txt ,
and run craft show:routes ,Still get the empty route list

**Comment by josephmancuso** [comment]
Something is wrong with your environment. Try deleting the project and making a new one. This hasn't been reported by anyone else and works fine for us with your zipped project and following your steps. We have narrowed down the issue to something with your computer or your environment
