### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by dsandber** [MasoniteFramework/masonite#303]
Going to:

https://docs.masoniteproject.com/

Results in a page:

Error 1016 Ray ID: [cut] • 2020-06-04 09:31:11 UTC
Origin DNS error
What happened?
You've requested a page on a website (docs.masoniteproject.com) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (docs.masoniteproject.com).

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS settings. If you are using a CNAME origin record, make sure it is valid and resolvable. Additional troubleshooting information here.

**Comment by josephmancuso** [comment]
this is back up

**Comment by josephmancuso** [comment]
It was an issue with Gitbooks DNS (our doc host)
