### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by tojorodialson** [MasoniteFramework/masonite#309]
For the future, its great to add in command `update` and `upgrade` for putting update or upgrading the framework.
And take easily multiple language in structure. Ex: fr, en, ...)

**Comment by josephmancuso** [comment]
@tojorodialson are you familiar with how this would be done?

**Comment by josephmancuso** [comment]
I think this would be better done as a service or as a separate package. Not something that would fall under the Masonite umbrella. Theres enough work to be done on every major release that it would be a real pain to have to worry about making an upgrade for each one

**Comment by tojorodialson** [comment]
> @tojorodialson are you familiar with how this would be done?

No. This is my problem too with other program what I build
