### ISSUE TITLE
captureOutput test fails

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#313]
In the documentation it says you can [capture output](https://docs.masoniteproject.com/v/v2.3/useful-features/testing#getting-output) when testing. It provides the following example:

```python
def test_get_output(self):
    with self.captureOutput() as o:
        print('hello world!')

    self.assertEqual(o, 'hello world!')
``` 

I added this test to /tests/unit/test_works.py and ran it with `python -m pytest`

Instead of passing as expected, the test fails:

```python
_____________ TestUnit.test_get_output _____________ 
self = <test_works.TestUnit testMethod=test_get_output>

    def test_get_output(self):
        with self.captureOutput() as o:
            print('hello world!')
    
>       self.assertEqual(o, 'hello world!')
E       AssertionError: <_io.StringIO object at 0x7f21aa8f1d38> != 'hello world!'

tests/unit/test_works.py:16: AssertionError
```

**Comment by josephmancuso** [comment]
Will take a look tonight 👌

**Comment by josephmancuso** [comment]
Documentation is actually not correct. Correct example is:

```python
def test_get_output(self):
    with self.captureOutput() as o:
        print('hello world!')

    self.assertEqual(o.getvalue(), 'hello world!')
```

**Comment by josephmancuso** [comment]
will update the documentation

**Comment by tpow** [comment]
@josephmancuso I understand the important change is adding the `.getvalue()` call and this is a helpful addition to the documentation. However, the test *still* fails. In this case, it is because there is a line feed added by the print statement. One of these would be better:

```python
self.assertEqual(o.getvalue(), 'hello world!\n')
self.assertEqual(o.getvalue().rstrip(), 'hello world!')
```
