### ISSUE TITLE
Set Up  Github Sponsorship Tiers

### ISSUE THREAD

**Issue by mkeneqa** [MasoniteFramework/masonite#318]
**Is your feature request related to a problem? Please describe.**
Project owner(s) should consider having a GitHub sponsorship option.

**What do we currently have to do now?** 
Only Patreon.

**Describe the solution you'd like**
have at least three tiers with different monthly amounts to contribute to with varying incentives.

**Comment by Marlysson** [comment]
There's a Patreon for contribute with project: https://www.patreon.com/masonite

**Comment by mkeneqa** [comment]
I know there's patreon, but why not add github sponsorship as well? A lot the other projects have been doing it and it's nicely integrated within github - makes it easy to sponsor a project without having to jump to another site. I'd be more inclined to financially support this project if it had github sponsorship.

**Comment by josephmancuso** [comment]
@mkeneqa I submitted the sponsorship for approval from GitHub. Just a waiting game now
