### ISSUE TITLE
Refinements to route arguments and when they can be omitted

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#321]
I'm trying to make sense of what the [documentation for route](https://docs.masoniteproject.com/the-basics/views#route) is saying. It says "if the current route already contains the correct dictionary then you do not have to pass a second parameter." I'm not sure I understood that. I think it is saying that if the current URL already has the value and uses a route with a similar parameter name you don't need to pass it. For example, if I'm on /dashboard/1/ and have a route to /dashboard/@id/users on that view, it will recognize the id. If so, that's neat, but only mildly useful. Am I understanding it correctly? Is there more to it?

The following is probably a feature request, but is what I tried to get working based on (misunderstanding?) the documentation.

What I'd like is for routes to know the context and know about object's properties. It would be nice if you pass a model it would work out the correct parameter based on the route and the model's attributes.

For example, if I have a route like `Get('/user/@id', 'UsersController@show').name('user')` and a template:

```jinja2
<ul>
{% for user in users %}
   <li><a href="{{ route('user', [user]) }}">{{ user.name }}</a></li>
{% endfor %}
</ul>
```

It would be nice if the route recognized that the user model has an "id" column/attribute that matches the `@id` on the route and uses it instead of needing to specify user.id. Of course, if user.id is specified it should use it.

I initially thought that the route would know the context and that all arguments could be omitted (eliminate the [user] in the template above). Although that would feel magical in templates, I'm thinking it would be hard to understand what's happening and difficult to debug.

**Comment by josephmancuso** [comment]
@tpow yeah I am hesitant on making things too magical. I think what you want is how Laravel does route model binding. Since Masonite 3.0 is going to change the ORM I think we should hold off on what this is trying to do for now

**Comment by josephmancuso** [comment]
This is no longer the case anyway in Masonite 4
