### ISSUE TITLE
request.referrer

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#323]
For convenience and because it is typical in other frameworks, it would be helpful to provide the "HTTP_REFERER" on the request object as request.referrer.

It looks like this would be a simple change in request.py, possibly setting it in load_environ.
`self.referrer = environ.get('HTTP_REFERER')`

I'd be glad to create a pull request for this.

This is not a breaking change.

**Comment by josephmancuso** [comment]
Added this in 2.3.14
