### ISSUE TITLE
Masonite package does not contain "QueueDatabaseDriver" in file "masonite.providers.QueueProvider.py"

### ISSUE THREAD

**Issue by marcelovieirahonorio** [MasoniteFramework/masonite#325]
**Describe the bug**
I install masonite from *pip3 install* and configure the *.env* file to use QUEUE_DRIVER=database.
But the application dont work.
To solve, I see the source in github and edit the file: "<<venv path>>/lib/python3.8/site-packages/masonite/providers/QueueProvider.py" , change/add the lines:

Line 4: change to:
from ..drivers import QueueAsyncDriver, QueueAmqpDriver, QueueDatabaseDriver

Line 17: add: 
        self.app.bind('QueueDatabaseDriver', QueueDatabaseDriver)

After this, the Queue works correctly with Database tables.

**To Reproduce**
1. Install the Masonite with pip3 (tested with version 2.3.16 on Ubuntu and 2.3.13 on Ubuntu WSL2)
2. Change the setting QUEUE_DRIVER in ".env" to value "database"
3. Try run the queue:work:  *craft queue:work --driver database*
4. See the error about the DatabaseDriver not installed

**Expected behavior**
I want run Queue with database driver. If change the file installed by pip3 as above, works.

**Comment by josephmancuso** [comment]
Oh how odd. Is this something you can change for me? If not I can fix it tonight

**Comment by josephmancuso** [comment]
Fixed in 2.3.17. Please upgrade your Masonite version

**Comment by marcelovieirahonorio** [comment]
Thank you for publish the new version.
I had test it and the QueueDatabaseDriver worked correctly!!!

**Comment by josephmancuso** [comment]
love it ❤️
