### ISSUE TITLE
craft queue:table does nothing

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#329]
**Describe the bug**
According to the [documentation](https://docs.masoniteproject.com/useful-features/queues-and-jobs#failed-jobs) I can store failed jobs in database using:
```
$ craft queue:table
```
Once done, I have this as output.
```
> Migration created successfully
```
That's fine but no migration is created. I think the issue is [here](https://github.com/MasoniteFramework/masonite/blob/2.3/src/masonite/commands/QueueTableCommand.py#L18). We can remove all the options from that command or have 3 ways to run that command:
```
$ craft queue:table 
$ craft queue:table --failed
$ craft queue:table --jobs
```

**Comment by josephmancuso** [comment]
what should be the default?

**Comment by nioperas06** [comment]
The first one.

**Comment by allanfreitas** [comment]
I think if we follow the logic here, we always create the "jobs" table first cause without Jobs there's no failed jobs.

My 2 cents, it's to put eh jobs table as default.

We could create another command for failed jobs like:
```
$ craft queue:failed-table
```

**Comment by josephmancuso** [comment]
I actually like the idea of a new command specifically for the failed table

**Comment by josephmancuso** [comment]
This is done in Masonite develop branch
