### ISSUE TITLE
OPTIONS request got blocked

### ISSUE THREAD

**Issue by erhuabushuo** [MasoniteFramework/masonite#330]
CORS scenarios， browser make an options request automatically,  but masonite does not response.

**Comment by josephmancuso** [comment]
You'll have to use a stronger server for development. Unfortunately the current Masonite dev server can't handle 2 requests at the same time. 

can use something like gunicorn:

```
$ pip install gunicorn
$ gunicorn wsgi:application --reload
```

**Comment by erhuabushuo** [comment]
Thanks a alot
