### ISSUE TITLE
Create an Inertia.js adapter

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite#331]
I have seen that there is an Inertia.js adapter as a gist here developed by @josephmancuso 
https://gist.github.com/josephmancuso/6528fe8ef9cb2f6cf25ccd19852ee7f1

**What do we currently have to do now?** 
we need to copy the gists files to integrate that into a project

**Describe the solution you'd like**
- I guess we should migrate this into a proper package
Also I have seen on Masonite Slack that _João Magalhães_ started to work on it like 4 months ago. What is the current status ? 

- I did not look into it in details, but maybe obvious path then is to add missing features (existing in laravel adapter) if any !

I would be glad to contribute 💪

**Comment by girardinsamuel** [comment]
Good idea ! What about repo on GitLab 😄 ? Maybe it would better to input the full url ?
From which branch should I open a PR if I do it next days ?

**Comment by girardinsamuel** [comment]
I've given some thoughts, It would be cool indeed to add the `--repo` to `craft new` command.
But maybe, it would be also nice to add **a package or a preset** to install / configure inertia.js adapter into an existing Masonite project ?

I guess a package would be a better fit as we need to install a new provider, copy a new config file, a new middleware and some core modules (version, response) which could be imported from the installed package.

What do you think ? 🤔

**Comment by josephmancuso** [comment]
Yes a new package is really the way to go

**Comment by girardinsamuel** [comment]
> Yes a new package is really the way to go

Under MasoniteFramework namespace ? I can open a PR to add your gist as a package with install command if you create the repo.

**Comment by girardinsamuel** [comment]
The first alpha version of the adapter has been released. 🎉 

**Next steps:** 
- Finish the [PingCRM demo](https://github.com/girardinsamuel/pingcrm-masonite)
- Add unit tests
- Write/Clarify documentation
- Fix/Improve scaffolding small demo with two components to play with it
