### ISSUE TITLE
Pagination is not Working.

### ISSUE THREAD

**Issue by yubarajshrestha** [MasoniteFramework/masonite#333]
**Describe the bug**
paginate(length) is returning expected json but query doesn't works the same. Like whether `page` parameter is 1 or 2 or anything it returns same database result but the current_page, page etc. are working.

**Comment by josephmancuso** [comment]
Can I see your code? The pagination is not automatic. You will need to specify the pagination. Something like this:


```python
    def show(self, view: View, request: Request):
        """Show the welcome page.

        Arguments:
            view {masonite.view.View} -- The Masonite view class.
            request {masonite.request.Request} -- The Masonite request class.

        Returns:
            masonite.view.View -- The Masonite view class.
        """
        return User.paginate(int(request.input('per_page', 20)), int(request.input('page', 1)))
```
