### ISSUE TITLE
Adding routes from files other than web.py

### ISSUE THREAD

**Issue by nicolaipre** [MasoniteFramework/masonite#349]
Hi.

I cannot seem to find out how I can make Masonite load routes from other files than `routes/web.py`.

I want all my API routes registered in `routes/api.py`. 

Based on what I have read and looked up, it seems like an older version of Masonite had this? Are there any ways of including routes this way, such that they show up with `craft show:routes`?

Also, love the framework! Beats any other Python Web framework I have ever used.

**Comment by josephmancuso** [comment]
older versions did have that functionality. If you want routes in other files simply build your routes there and then import them to `web.py` file like this:

```
# routes/api.py

ROUTES = [
    RouteGroup([
         Get('/', ..),
         Post('/', ..),
         Put('/', ..),
         ...

    ], prefix="/api")
]
```

and then inside web.py you can just import it and append it to the list:

```python
# routes/web.py
from .api import ROUTES as APIRoutes

ROUTES = [
    # normal routes here
]

ROUTES += APIRoutes
```

Something like that

**Comment by nicolaipre** [comment]
Thank you for the clarification, Joseph!
