### ISSUE TITLE
Unable to seed

### ISSUE THREAD

**Issue by pratamatama** [MasoniteFramework/masonite#364]
**Describe the bug**
An error message throwns with no stackTrace when running `craft seed:run` and `craft seed:run User`
Error Message: `The filename, directory name, or volume label syntax is incorrect.`

**To Reproduce**
1. Craft a new masonite project
2. Create a new database for new masonite project
3. Edit .env to use the new database
4. Run command `craft migrate`
5. Run command `craft seed:run` or `craft seed:run User`
6. See the error

**Expected behavior**
The command should not throw an error and should execute the prebuilt
`database_seeder.py` as well as `user_table_seeder.py`.

**Screenshots**
![image](https://user-images.githubusercontent.com/42239243/98762501-5b99a180-240a-11eb-9d82-d1c6f168f134.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro [10.0.19042 N/A Build 19042]
 - Browser: -
 - Version: Masonite 2.3

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -
 - Browser: -
 - Version: -

**Additional context**
No additional context.

**Comment by Marlysson** [comment]
@pratamatama Did you tried `python craft seed ... " ?

**Comment by josephmancuso** [comment]
This is a windows issue but I don't have a windows machine to replicate this.

You will need to run seeds using orator directly.

```
orator db:seed -p databases/seeds -c config/database.py -f
```
