### ISSUE TITLE
Upgrade NPM dependencies

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#370]
need to make sure npm packages are up to date.

when running npm install i am getting this 

```
added 1037 packages from 486 contributors and audited 1122 packages in 25.055s

52 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

When running npm audit fix i get this:

```
fixed 0 of 2 vulnerabilities in 1122 scanned packages
  2 package updates for 2 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```

**Comment by josephmancuso** [comment]
This is only for Masonite 3 and should be fixed in the cookie-cutter repo on the 3.0 branch

**Comment by josephmancuso** [comment]
Also getting this error when using tailwindcss:

```
Error: PostCSS plugin tailwindcss requires PostCSS 8.
```

Might be because of some out datted dependencies

**Comment by girardinsamuel** [comment]
@josephmancuso 

Yes for latest Tailwind 2.0 version if there is an issue we need to follow their updating guidelines : 
https://tailwindcss.com/docs/installation#post-css-7-compatibility-build
which is tlrd : 
```
npm uninstall tailwindcss postcss autoprefixer
npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
```

**Comment by girardinsamuel** [comment]
@josephmancuso If you did not start this, I guess I can do this because there are some packages updates to do also for the vue 3.0 preset, I have added recently ( among which Laravel Mix, because new version 6.0 is released )

**Comment by girardinsamuel** [comment]
@josephmancuso I fixed the dependencies on this repo (for Vue 3 preset only) and on the cookie-cutter repo for the basic dependencies.

Latest tailwindcss version is working correctly if we install it because PostCSS has been upgraded

**Comment by girardinsamuel** [comment]
I close this one now that PR has been merged.
