### ISSUE TITLE
Wrong http status code

### ISSUE THREAD

**Issue by imlison** [MasoniteFramework/masonite#372]
**Describe the bug**
When sending a POST request to the GET route, it should display "Method Not Allowed", but now it displays "Not Found".

**To Reproduce**
1. craft new testproj
2. craft serve
3. curl -d "" http://127.0.0.1:8000/

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Win10

**Comment by imlison** [comment]
The problem lies in the line 124 of masonite/providers/RouteProvider.py. Setting the status to 405 does not work because the status has been set in line 121, and response.vew will not overwrite the status.

**Comment by josephmancuso** [comment]
I think the solution is to just throw it inside an if statement then:

```python
        # If the route exists but not the method is incorrect
        if request.is_status(404) and request.route_exists(request.path):
             response.view("Method not allowed", status=405)
        else:
            response.view("Route not found. Error 404", status=404)
```

Could you open a pr for this?

**Comment by imlison** [comment]
merged
