### ISSUE TITLE
some request helpers are gone

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite#379]
**Describe the bug**
@josephmancuso  some request helpers `with_success` and `with_flash` are gone. I have added those in 2.3.18, there are gone in Masonite 3.0 since you refactor the request/response modules.

Is it intended ? 
It was in this PR, along with some tests :
https://github.com/MasoniteFramework/masonite/pull/346/files#diff-79423f125b112fb292b05a2ba9a5597c1985e62a213f9cb4536c9501a94032a0R955

I liked those shortcuts which (i think) were in the Masonite spirit ❤️  !

Thanks

**Comment by josephmancuso** [comment]
umm i have no idea where they went 😅

**Comment by josephmancuso** [comment]
how do you know they were in 2.3.18? I don't them see in the diff

**Comment by josephmancuso** [comment]
i see it in your commit but when i check the request class on the 2.3.18 tag .. they're not there lol https://github.com/MasoniteFramework/masonite/blob/v2.3.18/src/masonite/request.py

**Comment by josephmancuso** [comment]
oh i found it. its here https://github.com/MasoniteFramework/masonite/pull/357/files

**Comment by girardinsamuel** [comment]
ah yes you're right it has not been merged yet lol

**Comment by girardinsamuel** [comment]
@josephmancuso you released it in 2.X but those changes are not in Masonite 3, is it okay if reopen this PR targeting develop ?

**Comment by josephmancuso** [comment]
sure
