### ISSUE TITLE
Back method should redirect back with the query string

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#382]
I found it surprising that the back() helper when in a template doesn't populate with the current URL including the query string, but instead is the path portion of the URL. Shouldn't back be the current page's URL? Otherwise it isn't "back".

However, I went ahead and worked around this by constructing the desired URL by calling back with the URL. In a template it looks something like this: `{{ back('/test?var=a') }}`

Looking at the page source it now shows the __back hidden field with the desired URL.

Unfortunately, this doesn't work. It looks to me like this is a similar problem that drove #327. In the request.back function, it always calls self.redirect(parameter). This means that it is assuming the parameter is a route and it then tries to process parameters (which doesn't work because none were provided and the query string question mark looks like an optional parameter). 

I think all the calls to request.redirect in request.back need to be using the url= keyword argument instead so they work with query strings.

**Comment by josephmancuso** [comment]
Still requires adding the request query string by default

**Comment by tpow** [comment]
Perhaps something like this in back() in the view helper:

```python
        if intended_route:                                                       
            location = intended_route                                            
        else:                                                                    
            location = request.path
            qs = request.query_string()                                              
            if qs:                                                                   
                location = "{}?{}".format(location, qs)
```

(The last three lines are new.)

**Comment by josephmancuso** [comment]
will need to make sure this is the case with M4

**Comment by girardinsamuel** [comment]
It's implemented for Masonite 4 ! 🚀
