### ISSUE TITLE
Routing Rewrite

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#394]
Masonite 4 will have a new routing engine as well as new routing syntax.

We will have a route syntax like this:

```python
from masonite.routes import Route

Route.get('/url/1', 'Controller@show')
Route.post('/url/2', 'Controller@show')
Route.group(
    Route.get('/url/3', 'Controller@show')
    Route.post('/url/4', 'Controller@show')
)
```

The routing engine will be a simple `Route` class with a few helper methods on it. It will support all features of the current routing engine such as compilers, regex, `@` style parameters (`/users/@id`) groups, deeper module controllers, global controllers, object based controllers, etc.

Currently every route is its own class (Get(), Post(), etc) and we have to loop through all of them to find a match. Now we will have a simple `find('/request/path')`. This abstracts a lot of the logic out and comes a single point of maintenance. Speed improvements, bug fixes, etc will be done there. This is a much simpler approach. Finding a route now becomes:

```python
request.path #== /dashboard/1

Route.find(request.path) #== finds the route that matches the current path
```

**Comment by girardinsamuel** [comment]
I guess a helper would be available too, to do it the other way around ?
=> from name to path, with url parameters if there are any
```python
Route.reverse("auth.user", id=2)  #== /user/2
# or Route.reverse("auth.user", {"id": 2})  #== /user/2
```
in tests I often need to get url with params (both URL params such as the user id in previous example **and** GET parameters) so I end up in Django in doing
```python
f"{reverse("auth.user", kwargs={"id": 2})}/?search=John"
```
and it bothers me to have to write this, so the reverse lookup could be able to handle required url params and additional get params, maybe like:

```python
Route.reverse("auth.user", {"id": 2}, {"search": "John"})  #== /user/2?search=John
Route.reverse("auth.user", params={"id": 2}, query={"search": "John"})  #== /user/2?search=John
```

**Comment by josephmancuso** [comment]
what exactly is `reverse` doing? lol? You are trying to get the compiled URL?

**Comment by girardinsamuel** [comment]
yes. I am using this a lot in Django in tests to test a specific controller without hard-coding the url, I am providing the name and the reverse function outputs the url which is then used by the test to make a request against

**Comment by girardinsamuel** [comment]
More info here https://docs.djangoproject.com/en/3.1/ref/urlresolvers/#reverse

**Comment by tpow** [comment]
@girardinsamuel How is `reverse` different from the `route` helper that is already in Masonite? It looks like the same thing to me. I'm already using it all over the place in views and controllers. See https://docs.masoniteproject.com/the-basics/views#route

I don't think this is mentioned on the Routing page in the documentation, but probably should be.

**Comment by girardinsamuel** [comment]
> @girardinsamuel How is `reverse` different from the `route` helper that is already in Masonite? It looks like the same thing to me. I'm already using it all over the place in views and controllers. See https://docs.masoniteproject.com/the-basics/views#route

It's the same thing but available as a method in code and not only a view helper. Maybe it's already available but as here we are talking about a rewrite, I was thinking that this kind of helper should belong to the `Route` class shown above.

**Comment by tpow** [comment]
Although I understand the idea of basing this on one class, I don't like repeating "Route." everywhere. It would be nice to keep a syntax similar to what is there now as it is clear and direct. Perhaps Get, Put, etc. could be aliases for the equivalent Route.get, Route.put, etc. so the syntax wouldn't need to change much?

**Comment by josephmancuso** [comment]
done in M4
