### ISSUE TITLE
Missing vue-stubs in masonite3

### ISSUE THREAD

**Issue by egwald** [MasoniteFramework/masonite#395]
**the command "craft preset vue" ends with a error:**

 craft preset vue

Scaffolding Application ...

  FileNotFoundError

  [Errno 2] No such file or directory: '*/venv/lib/python3.9/site-packages/masonite/commands/presets/vue-stubs/webpack.mix.js'

  at /usr/lib/python3.9/shutil.py:261 in copyfile
       257│ 
       258│     if not follow_symlinks and _islink(src):
       259│         os.symlink(os.readlink(src), dst)
       260│     else:
    →  261│         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
       262│             # macOS
       263│             if _HAS_FCOPYFILE:
       264│                 try:
       265│                     _fastcopy_fcopyfile(fsrc, fdst, posix._COPYFILE_DATA)

In the lib no vue-stubs:

![grafik](https://user-images.githubusercontent.com/8221345/105060555-d4efe900-5a78-11eb-9a50-56ada2fd44a8.png)

**Comment by nioperas06** [comment]
I think adding `vue-stubs` in https://github.com/MasoniteFramework/masonite/blob/3.0/MANIFEST.in should fix this issue.

**Comment by nioperas06** [comment]
It might be a good idea to make a package for frontend scaffolding and remove it from the core like https://github.com/laravel/ui.
