### ISSUE TITLE
Global Timezone Configuration

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/masonite#405]
Hello,

I would like to request a configuration that sets the timezone of the app. I think it will also affect MasoniteORM. And if possible, if this will also automatically override the timezone of ```pendulum``` or any DateTime library Masonite is currently using.

Thanks!!!!

**Comment by josephmancuso** [comment]
I will take a look if this is possible. I don't have ownership of pendulum so not sure if its possible with pendulum

**Comment by josephmancuso** [comment]
@jpmateo022 looking at this issue again now i'm not sure Masonite uses any timezones? If you are talking about the ORM and database part, Masonite ORM has a `__timezone__` attribute you can set on models to set the timezone there.

If you want it more "globally" you can set a base model and set the `__timezone__` on the base model and then inherit the base model on all your other models
