### ISSUE TITLE
craft info bug application._version missing

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/masonite#407]
Hi,

Upon executing ```craft info```, it throws this error.

![image](https://user-images.githubusercontent.com/26633918/106224526-78ca5900-621e-11eb-86ff-fd5fb6fa0fa6.png)

**Comment by jpmateo022** [comment]
Im using masonite 3.0.6

**Comment by girardinsamuel** [comment]
Yes I got this one too, I'll fix this soon 😉

**Comment by jpmateo022** [comment]
Hi, may I know if this is already fixed?

**Comment by girardinsamuel** [comment]
Wooops I didn't do it ! I'll open a PR 😉
