### ISSUE TITLE
Array form input not being parsed as list of dictionary

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/masonite#412]
I have this form inputs

![image](https://user-images.githubusercontent.com/26633918/106409539-b4159380-647b-11eb-85d7-e945c2cfe36d.png)

But when I retrieve it in the backend via request. I'm getting a False value

```
form   = request.input('form')
```

But when I do this

```
for = request.input('form[9e14c663280d84fb6288396360ae9dbe]')
```

I get the value.

**Comment by girardinsamuel** [comment]
You did this through Postman, but how would do this in your frontend in the first place ?
```
let form = new FormData()
form.append("form", {
     "9e14...": "value",
     "9e14...": "other_value",
})
```
?

**Comment by jpmateo022** [comment]
I normally do this if I want to use form arrays
```
var form_data = new FormData();

form_data.append(`my_input[${id}][field1]`,value);
form_data.append(`my_input[${id}][field2]`,value);
form_data.append(`my_input[${id}][field3]`,value);

```
