### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split' in masonite response.json()

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/masonite#413]
Hi,

Related to this issue.
https://github.com/MasoniteFramework/orm/issues/346

My scenario in this is in my controller im using response.json and the in the frontend Im doing long pooiling every 5000 seconds.

When I use this kind of response.

```
            return response.json({
                'code': 200,
                'message': 'SUCCESS',
                'data': True
            },200)
```

Im getting the error, but when I changed it to 

```
            return {
                'code': 200,
                'message': 'SUCCESS',
                'data': True
            }
```

Im not getting anymore the error.

**Comment by jpmateo022** [comment]
I'll try a different environment to see if I will still encounter the issue.

**Comment by girardinsamuel** [comment]
According to https://docs.masoniteproject.com/advanced/responses#json-responses
```
return response.json({
                'code': 200,
                'message': 'SUCCESS',
                'data': True
            })
```
is the same as doing
```
 return {
                'code': 200,
                'message': 'SUCCESS',
                'data': True
            }
```

But about setting the response status code, it's documented you can do 
https://docs.masoniteproject.com/advanced/responses#setting-status-codes
```
return "string", 200
```
But I am not sure that it's working when returning a dict.
Finally when returning response.json(), the signature is response.json(payload, status=200), so the default is already 200,
but it should work with an other status code.

**Comment by girardinsamuel** [comment]
I was not able to reproduce the issue either...
Your return this response from which method ? (POST, GET, ...) ?

Is it working in you web browser ? in Postman ?

**Comment by jpmateo022** [comment]
The request is being done via Ajax request. I'm suspecting now it's my database connection. I'm just currently finishing the development in my local then I'll test it in the test environment.

**Comment by jpmateo022** [comment]
I found out now the problem and it's not Masonite.  I tried removing threads in my gunicorn and I don't receive the errors anymore.
