### ISSUE TITLE
Error in fresh install

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/masonite#415]
![image](https://user-images.githubusercontent.com/26633918/107107462-10a5f380-686c-11eb-9468-c4b7254c0078.png)

**Comment by josephmancuso** [comment]
Hmm how did you run the install? Is that not inside the requirements.txt file?

**Comment by girardinsamuel** [comment]
Weird because I have just tried to do it and I got no issues.
My setup was maybe different, here is how I proceeded:
1. create a new venv and activate it
2. `pip install masonite`
3. `craft new`
4. `pip freeze` gives me:
```
masonite==3.0.6
masonite-dot==0.0.5
masonite-logging==1.0.1
masonite-orm==1.0.22
masonite-validation==3.0.13
```
In the project requirements.txt I have:
```
masonite>=3.0,<4.0
masonite-logging>=1.0,<2.0
masonite-validation>=3.0,<4.0
```

**Comment by girardinsamuel** [comment]
@jpmateo022 I think the exception caught might be broad because the error seems to come from "No module named pip".
Did you try to run `pip ...` with your current python interpreter ? It seems that masonite can't find it to install required packages.

**Comment by girardinsamuel** [comment]
@jpmateo022 what's the status on this ? Is is still an issue ?

**Comment by girardinsamuel** [comment]
I am closing it for now. But can reopen this issue at any time if needed.
