### ISSUE TITLE
File Extension not Supported

### ISSUE THREAD

**Issue by ghost** [MasoniteFramework/masonite#423]
While trying to upload a file, I encountered a weird error. Everything was working perfectly but in the case of the file with the extension. JPG (ALL CAPS) file upload is giving me an error.

**To Reproduce**
1. Get any image with .JPG extension and try to upload it

```python
upload.driver('disk').store(fingerprint, location="storage/fingerprints")
```

Error: The file extension is not supported.

![IMG_2249](https://user-images.githubusercontent.com/67942433/109835636-7dde5600-7c6b-11eb-9a5b-e2184b4e3942.JPG)

**Comment by josephmancuso** [comment]
Can you upgrade to 3.0.9 and try again?

**Comment by ghost** [comment]
> Can you upgrade to 3.0.9 and try again?

masonite version?

**Comment by josephmancuso** [comment]
Yeah there was a fix to cast the image types to lowercase before checking. I think that will fix this issue

**Comment by ghost** [comment]
No matching distribution found! masonite==3.0.9

**Comment by josephmancuso** [comment]
should be there .. try again maybe? Maybe it needed a few minutes to propagate. 

If that doesn't work you might need to pass the `--no-cache-dir` flag when installing via pip to get around your local cache

**Comment by josephmancuso** [comment]
Will close this issue but can reopen if there are any further issues
