### ISSUE TITLE
pytest returning ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/masonite#426]
from masonite.testing import TestCase

but when using

from unittest import TestCase

its working fine

both tried

python -m pytest and pytest

**Comment by jpmateo022** [comment]
![image](https://user-images.githubusercontent.com/26633918/112122672-7cb1a080-8bfb-11eb-9887-5da1b25a08da.png)

**Comment by girardinsamuel** [comment]
It's a regression bug, I reproduced it on masonite latest version 3.0.9. We will fix this 😉
