### ISSUE TITLE
relation table does not exist during I testing database

### ISSUE THREAD

**Issue by OnePieceLv** [MasoniteFramework/masonite#440]
**Describe the bug**
Not found table when I testing the database
I use the Postgres database for my test database and define it in the .env.testing file

**To Reproduce**
I create a [demo project](https://github.com/OnePieceLv/masonite-3.0-demo/tree/main
) for replicate

if you want to fix it, just uncomment `from tests.BaseTestCase import BaseTestCase as TestCase`.

**Expected behavior**
if the migration file had running, the table should be found. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3759810/118483084-320a5b80-b748-11eb-93ee-dbccf479a534.png)

![image](https://user-images.githubusercontent.com/3759810/118483124-3df61d80-b748-11eb-875e-ccb28c3db18e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Terminal: oh-my-zsh
 - Version: Big Sur

**Additional context**

**Comment by OnePieceLv** [comment]
I fixed it though replace the `Migrations` file that import from `masonite.helpers.migrations` with my custom Migrations file

**Comment by OnePieceLv** [comment]
In the custom Migration file, the only diff just pass `connection` parameter to `Migration()`

![image](https://user-images.githubusercontent.com/3759810/118487311-2a998100-b74d-11eb-8591-fd50c65728e5.png)
![image](https://user-images.githubusercontent.com/3759810/118487587-751afd80-b74d-11eb-89a6-6d52ec0aa539.png)

**Comment by josephmancuso** [comment]
This is fixed?
