### ISSUE TITLE
Laravel Mix Error

### ISSUE THREAD

**Issue by sn0rcha** [MasoniteFramework/masonite#451]
**Describe the bug**
Unable to get laravel mix working.

**To Reproduce**
1. craft new app
2. cd app
3. craft install
4. npm install && npm run dev

**Expected behavior**
```npm run dev``` to work

The following error shows:

```
[webpack-cli] Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.optimization.splitChunks.cacheGroups['styles-storage/compiled/css/style'] has an unknown property 'type'. These properties are valid:
   object { automaticNameDelimiter?, automaticNameMaxLength?, automaticNamePrefix?, chunks?, enforce?, enforceSizeThreshold?, filename?, maxAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name?, priority?, reuseExistingChunk?, test? }
 - configuration.output.chunkFilename should be a string.
   -> The filename of non-entry chunks as relative path inside the `output.path` directory.
 - configuration.stats has an unknown property 'preset'. These properties are valid:
   object { all?, assets?, assetsSort?, builtAt?, cached?, cachedAssets?, children?, chunkGroups?, chunkModules?, chunkOrigins?, chunks?, chunksSort?, colors?, context?, depth?, entrypoints?, env?, errorDetails?, errors?, exclude?, excludeAssets?, excludeModules?, hash?, logging?, loggingDebug?, loggingTrace?, maxModules?, moduleAssets?, moduleTrace?, modules?, modulesSort?, nestedModules?, optimizationBailout?, outputPath?, performance?, providedExports?, publicPath?, reasons?, source?, timings?, usedExports?, version?, warnings?, warningsFilter? }
```

Node.js v14.7.4
Masonite 3.0.12

Any ideas?

**Comment by yubarajshrestha** [comment]
> **Describe the bug**
> Unable to get laravel mix working.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. craft new app
> 2. cd app
> 3. craft install
> 4. npm install && npm run dev
> 
> **Expected behavior**
> `npm run dev` to work
> 
> The following error shows:
> 
> ```
> [webpack-cli] Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
>  - configuration.optimization.splitChunks.cacheGroups['styles-storage/compiled/css/style'] has an unknown property 'type'. These properties are valid:
>    object { automaticNameDelimiter?, automaticNameMaxLength?, automaticNamePrefix?, chunks?, enforce?, enforceSizeThreshold?, filename?, maxAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name?, priority?, reuseExistingChunk?, test? }
>  - configuration.output.chunkFilename should be a string.
>    -> The filename of non-entry chunks as relative path inside the `output.path` directory.
>  - configuration.stats has an unknown property 'preset'. These properties are valid:
>    object { all?, assets?, assetsSort?, builtAt?, cached?, cachedAssets?, children?, chunkGroups?, chunkModules?, chunkOrigins?, chunks?, chunksSort?, colors?, context?, depth?, entrypoints?, env?, errorDetails?, errors?, exclude?, excludeAssets?, excludeModules?, hash?, logging?, loggingDebug?, loggingTrace?, maxModules?, moduleAssets?, moduleTrace?, modules?, modulesSort?, nestedModules?, optimizationBailout?, outputPath?, performance?, providedExports?, publicPath?, reasons?, source?, timings?, usedExports?, version?, warnings?, warningsFilter? }
> ```
> 
> Node.js v14.7.4
> Masonite 3.0.12
> 
> Any ideas?

Everything looks okay on mine with following versions:
```shell
Node: v14.17.4
Masonite: 3.0.12
```

Did you change anything in webpack configurations?
