### ISSUE TITLE
fresh installation gives error. and how to with nginx ?

### ISSUE THREAD

**Issue by magic-thomas** [MasoniteFramework/masonite#452]
I just want to try this interesting framework.  

After fresh installation, and ran 'craft serve' in mac,  I got error. 

```sh
problem in config.providers - ModuleNotFoundError: No module named 'masonite.validation'
```

And how can masonite  go with nginx ?

How can I set nginx configuration file, specially about document root ?

**Comment by josephmancuso** [comment]
Do you have masonite-validation in your requirements.txt file? And did you install via this file?

Also there's a few guides out there you can Google but here's one. The Masonite 2 and 3 guide for Nginx should be similar. https://dev.to/holiccl/deploying-masonite-2-project-with-nginx-and-gunicorn-3pnj
