### ISSUE TITLE
How to use multiple languages?

### ISSUE THREAD

**Issue by goophps** [MasoniteFramework/masonite#453]
How to use multiple languages? I want to develop a project in different national languages, but it seems that this framework does not support multiple languages.

**Comment by girardinsamuel** [comment]
Indeed for now there is no i18n module in Masonite.
@josephmancuso did you have in mind to add this feature one day ?

**Comment by goophps** [comment]
> 实际上，目前 Masonite 中没有 i18n 模块。
> @josephmancuso你有没有想过有一天要添加这个功能？

I look forward to your masonite-admin

**Comment by josephmancuso** [comment]
One day yeah. No development plans for it currently

**Comment by josephmancuso** [comment]
We will get to this when we can. No reason to keep issue open. No rush on it but if anyone wants to create a package for it you have my support. I will contribute to it as well
