### ISSUE TITLE
Setting the hostname with `python craft serve -b 0.0.0.0` does not work

### ISSUE THREAD

**Issue by StevenMHernandez** [MasoniteFramework/masonite#472]
**Describe the bug**

`python craft serve -b 0.0.0.0` does not serve the application using the specified host `0.0.0.0`.

**To Reproduce**
 
1. `pip install masonite==4.0.2`
2. Create a new masonite project: `cd masonite-v3-serve && mkdir masonite-v3-serve && project start .`
3. `python craft serve`
    1. This results in the following output: `Serving on http://localhost:8000` (This works)
4. `python craft serve -b 0.0.0.0`
    1. This results in the following output: `Serving on http://localhost:8000` (This does not work)
4. `python craft serve --host 0.0.0.0`
    1. This results in the following output: `Serving on http://0.0.0.0:8000` (This works)

You can see that `-b` does not work as expected but `--host` does work.

**Thoughts**

Digging into the new [v4 ServeCommand](https://github.com/MasoniteFramework/masonite/blob/4.0/src/masonite/commands/ServeCommand.py) I noticed there may be some other problems too. The current main function contains

```
    if "--host" in args:
        host = args[args.index("--host") + 1]
    if "--port" in args:
        port = args[args.index("--host") + 1]
    if "-p" in args:
        port = args[args.index("-p") + 1]
```

1. There is no if statement for `-b`
2. The `--port` if statement uses `args.index("--host")` instead of `args.index("--port")`

I will try to send a pull request to fix this later on.

**Comment by josephmancuso** [comment]
Looks like this just has to be updated here. Looks hard coded

https://github.com/MasoniteFramework/masonite/blob/f3088e124c40d0f9cd9de8f4518dd3ae4c296db6/src/masonite/commands/ServeCommand.py#L64
