### ISSUE TITLE
Create a way to exclude routes from middleware

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#474]
Need a way to specifically exclude routes from being assigned a middleware

**Comment by Marlysson** [comment]
Isn't the `exempt = [ ]` statement for this?

**Comment by josephmancuso** [comment]
Thats for excluding routes for CSRF protection. We need to exclude routes from being assigned certain middleware.

Think 5 routes inside a route group with the API middleware stack but one of those routes we don't actually want to have the api middleware stack assigned to it.
