### ISSUE TITLE
Mailable Bug

### ISSUE THREAD

**Issue by yubarajshrestha** [MasoniteFramework/masonite#477]
**Describe the bug**
I am not sure if this is a bug or it's just me having issue, but I am not able to make it work, following is the detailed code that I am using.

**UserRegistration Mailable**

```python
from masonite.environment import env
from masonite.mail import Mailable


class UserRegistration(Mailable):
    def build(self):
        return (
            self.subject("ACCOUNT REGISTRATION")
                .from_(env('MAIL_FROM_ADDRESS'))
        )
```

**Inside controller**

```python
        try:
            mailable = UserRegistration().set_application(application).to("test@example.com").text("Hello World")
            mail.send(mailable)
        except Exception as e:
            print("ERROR")
            print(str(e))
```

Note: I am using mailtrap.

**Exception is thrown**
```sh
ERROR
<app.mailables.UserRegistration.UserRegistration object at 0x104e65b50>
```

**Comment by josephmancuso** [comment]
@yubarajshrestha are you sure this is the error you are getting? This just looks like the mailable object you put as the error?

**Comment by girardinsamuel** [comment]
Also just FYI, the project template has been updated. Now the mail configuration is the following:
```python
from masonite.environment import env


FROM_EMAIL = env("MAIL_FROM", "no-reply@masonite.com")

DRIVERS = {
    "default": env("MAIL_DRIVER", "terminal"),
    "smtp": {
        "host": env("MAIL_HOST"),
        "port": env("MAIL_PORT"),
        "username": env("MAIL_USERNAME"),
        "password": env("MAIL_PASSWORD"),
        "from": FROM_EMAIL,
    },
    "mailgun": {
        "domain": env("MAILGUN_DOMAIN"),
        "secret": env("MAILGUN_SECRET"),
        "from": FROM_EMAIL,
    },
    "terminal": {
        "from": FROM_EMAIL,
    },
}
```
Then you don't have to specify `from_()` in your mailable. But of course you can do it to override it or for any other reasons.

**Comment by yubarajshrestha** [comment]
> ```python
> FROM_EMAIL = env("MAIL_FROM", "no-reply@masonite.com")
> 
> DRIVERS = {
>     "default": env("MAIL_DRIVER", "terminal"),
>     "smtp": {
>         "host": env("MAIL_HOST"),
>         "port": env("MAIL_PORT"),
>         "username": env("MAIL_USERNAME"),
>         "password": env("MAIL_PASSWORD"),
>         "from": FROM_EMAIL,
>     },
>     "mailgun": {
>         "domain": env("MAILGUN_DOMAIN"),
>         "secret": env("MAILGUN_SECRET"),
>         "from": FROM_EMAIL,
>     },
>     "terminal": {
>         "from": FROM_EMAIL,
>     },
> }
> ```

I do have the same configuration.

**Comment by yubarajshrestha** [comment]
![Screen Shot 2022-01-04 at 19 46 38](https://user-images.githubusercontent.com/7955362/148070403-1965552e-71fd-41a1-ba57-40219c3ca3c2.png)

**Comment by yubarajshrestha** [comment]
Following solution fixed the issue:

```python
 try:
            mailable = UserRegistration().set_application(application).to("test@example.com").text("Hello World")
            mail.mailable(mailable).send()
        except Exception as e:
            print("ERROR")
            print(str(e))
```
