### ISSUE TITLE
Add Hashing to the default user seeders

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#488]

**Comment by Marlysson** [comment]
Is this issue closed because of this line?

https://github.com/MasoniteFramework/cookie-cutter/blob/4.0/databases/seeds/user_table_seeder.py#L15

**Comment by girardinsamuel** [comment]
I would say yes ! @josephmancuso  ?

**Comment by josephmancuso** [comment]
yes. that line will store 2 different data types on 2 diff databases.

Postgres will store that as bytes and mysql will convert it to a string and store it

**Comment by girardinsamuel** [comment]
So we can close this no ?

**Comment by josephmancuso** [comment]
no. Hash.make() still needs to return a string

**Comment by girardinsamuel** [comment]
Should be solved here
https://github.com/MasoniteFramework/masonite/pull/492

**Comment by josephmancuso** [comment]
ooohhhh yeah I thought this was another ticket
