### ISSUE TITLE
add -a to Craft for all options at once

### ISSUE THREAD

**Issue by CptFry** [MasoniteFramework/masonite#489]
**Is your feature request related to a problem? Please describe.**
The Craft command has a bunch of nice options already, but there's no way that i'll remember it all. 

**What do we currently have to do now?** 
Right now I have to create a model, add a migration, then separately create a seeder. 

**Describe the solution you'd like**
add a new -a flag that creates a model, a controller, a migration with create and drop, and a seeder. 

**Describe alternatives you've considered**
Nope! 

- [ ] Is this a breaking change?
Shouldn't be! 

**Additional context**

**Comment by girardinsamuel** [comment]
This should be done in https://github.com/MasoniteFramework/orm/ repo, so I will transfer the issue.
