### ISSUE TITLE
WARNING: the 'package' argument is required to perform a relative import for '...app.User'

### ISSUE THREAD

**Issue by messiaqin** [MasoniteFramework/masonite#498]
**Describe the bug**
After initializing the project，execute "craft install" command。

WARNING: the 'package' argument is required to perform a relative import for '...app.User'
![image](https://user-images.githubusercontent.com/20896524/149861875-c03254f0-3e82-4a90-aeaa-d6b2bd5408c9.png)

execute "craft --version" command。
tips：craft --versionWARNING: No module named 'wsgi'
![image](https://user-images.githubusercontent.com/20896524/149861950-83eb15fe-3a3b-4210-85d1-e5441e6074fe.png)

**To Reproduce**
1. Craft new blog
2. cd blog
3. craft install

**Desktop (please complete the following information):**
 - OS: MAC Big Sur
 - Version 11.6
 - Python 3.8.9
 - pip3 21.3.1
 - Craft Version: 2.2.2
 - Masonite 2.3

**Comment by josephmancuso** [comment]
This is an older version of Masonite. Is there a reason you are installing Masonite 2.3? Is this an existing project?

**Comment by messiaqin** [comment]
It's an exercise  project，what's is the current  version? I'am install it by default command。

**Comment by messiaqin** [comment]
> This is an older version of Masonite. Is there a reason you are installing Masonite 2.3? Is this an existing project?

I check my package list, the Masonite version is 

`
masonite            2.3.26
masonite-dot        0.0.5
masonite-logging    1.0.1
masonite-validation 3.0.14
`

**Comment by josephmancuso** [comment]
Current version is 4.2.0. New projects at this should be using the latest version. v2.3 is no longer supported. 

Try version 4 for new projects
