### ISSUE TITLE
Add missing debug mode

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite#512]
In Masonite 3 we had `APP_DEBUG` env variable which could configure if debug mode was enabled or not.

- [ ] this should be added back as a parameter into `config/application.py`
- [ ] a helper `is_debug()` should be added in `application`
- [ ] the mode should be used to display exception page or error 500 page in case of error

Also how we use this with `APP_ENV` ? Should it be related ? Can we have environment equal to `production` and debug enabled ?

**Comment by josephmancuso** [comment]
So i believe APP_ENV only determined the environment (if you want to check for that) as well as loading `.env.{APP_ENV}` file in (if it exists)

**Comment by girardinsamuel** [comment]
yes I figured that out. So that's okay I will made a proposal for handling debug.
