### ISSUE TITLE
Improve `response.view()` method

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite#515]
`response.view()` cannot receive view template name as `View.render()` can.

It would be good to be able to do e.g. `response.view("errors.404", 404)`

**Comment by josephmancuso** [comment]
umm.. I think it would be hard to do this with the current signature right? What if you want to return an actual string?

**Comment by girardinsamuel** [comment]
maybe to avoid breaking change we could have:
```python
# right now it's:
response.view(view, status)
# we could modify to:
response.view(view, status, view_name=None)
# usage would be
response.view("hello world", 200)
response.view(view="welcome", status=200)
```

or wait M5 for a breaking change to have a better signature...
not a big deal

**Comment by josephmancuso** [comment]
not really sure the issue you are trying to solve with this

**Comment by girardinsamuel** [comment]
Hmm it's just to simplify things.
I found a bit weird to have to write `Response.view(View.render("auth:login"), 200)`. I feel I would like to write `Response.view("auth:login", 200)`

But that's not very important...

**Comment by josephmancuso** [comment]
ehh that tightly couples these 2 classes together. Not feeling this right now
