### ISSUE TITLE
`Route.add_controller_locations` is not working correctly

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/masonite#521]
This method is trying to load `Controller` instances from some python modules strings given in input.

The issue is that it's trying to load objects of type `src.masonite.controllers.Controller` and not `masonite.controllers.Controller`.
It's working correctly in the tests/integrations project of this repo but it's not working for packages.

It's working for normal projects though... So I am not sure what's the issue here.
I will continue looking into it.

**Comment by josephmancuso** [comment]
@girardinsamuel is this still an issue?
