### ISSUE TITLE
Mail notification driver is not using default mail driver defined in `config/mail.py`

### ISSUE THREAD

**Issue by Bindukarkee** [MasoniteFramework/masonite#532]
I am trying to implement notification feature in my application but it looks like the feature is yet in developing phase . 
Procedure:
1. Firstly, I created a notification Test
2. Then, used the channel mail for notification
3. When I used to_mail method inside notification, it printed mail in terminal.

Could  you please  guide  me how it can be resolved . 

When I went through the code, I found following code in mail driver:
![Screenshot from 2022-02-15 11-10-33](https://user-images.githubusercontent.com/20794268/153998295-c6844b24-f110-43c8-905e-0b03d3a1161a.png)

**Comment by girardinsamuel** [comment]
Hi ! Thanks for reporting this issue. Indeed something has been forgotten here.
We made a fix in the PR, we will release it soon.

👉 Now the default behaviour is to use default mail driver for sending mail notifications (`config/mail.py`).

And it's possible to override mail driver for a given notification by using `driver()` method of the Mailable:

```python
class CustomNotification(Notification, Mailable):
    def to_mail(self, notifiable):
        return (
            self.subject("Masonite 4")
            .from_("joe@masoniteproject.com")
            .text("Hello from Masonite!")
            # Here I am overriding the driver with `mailgun` else it will use default mail driver from `config/mail.py`.
            .driver("mailgun")
        )

    def via(self, notifiable):
        return ["mail"]
```

Doc has been updated here:
https://docs.masoniteproject.com/features/notifications#mail
