### ISSUE TITLE
Why are your software version numbers jumping so fast?

### ISSUE THREAD

**Issue by goophps** [MasoniteFramework/masonite#534]

**Comment by girardinsamuel** [comment]
Hi ! You can read more about Masonite release cycle here : https://docs.masoniteproject.com/prologue/release-cycle

Sometimes, some minor features are added from feature requests, and so we need to release a new minor increasing the second number.

**Comment by goophps** [comment]
I mean, you update very few features and the version number jumps fast. @girardinsamuel

**Comment by josephmancuso** [comment]
Lol we have been. See the change logs on the release page. Any time you see something in the added blocks the minor version will increase https://github.com/MasoniteFramework/masonite/releases
