### ISSUE TITLE
Unable to create task

### ISSUE THREAD

**Issue by Bindukarkee** [MasoniteFramework/masonite#539]
### Describe the bug

I am not able to create task using `craft` command.

### Expected behaviour

When I run `python craft task TaskName` a TaskName file should be created. But it's not.

### Steps to reproduce the bug

1. Create masonite project
2. Try to create task using craft command.

### Screenshots

```sh
FileNotFoundError

  [Errno 2] No such file or directory: '/home/kodiary/python_project/micro_service/nt/venv/lib/python3.9/site-packages/masonite/scheduling/commands/../../stubs/scheduling/Task.py'

  at venv/lib/python3.9/site-packages/masonite/utils/filesystem.py:65 in render_stub_file
      61│ 
      62│ 
      63│ def render_stub_file(stub_file, name):
      64│     """Read stub file, replace placeholders and return content."""
    → 65│     with open(stub_file, "r") as f:
      66│         content = f.read()
      67│         content = content.replace("__class__", name)
      68│     return content
      69│ 
```

### OS

Linux

### OS version

Ubuntu 18.04

### Masonite Version

4.6.3

### Anything else ?

:(

**Comment by girardinsamuel** [comment]
hi ! I can't reproduce the issue when running `python craft task MyTask`.

Do you have this line in your Kernel.py file?
```python
self.application.bind("tasks.location", "app/tasks")
```

**Comment by Bindukarkee** [comment]
Hi!
I do have self.application.bind("tasks.location", "app/tasks") , this line on my Kernel.py file

**Comment by josephmancuso** [comment]
@girardinsamuel is this missing from the MANIFEST.in file maybe? Maybe the stub file didn't come with the build

**Comment by girardinsamuel** [comment]
No I tried with the latest version on a new crafted project and it works !

**Comment by yubarajshrestha** [comment]
@josephmancuso @girardinsamuel are you guys using `ubuntu`?

**Comment by josephmancuso** [comment]
no thats a good point maybe a file location issue on linux?

**Comment by girardinsamuel** [comment]
Yep it's happening on Linux, I have reproduced it. It's an issue with case of file. I will fix it asap !
