### ISSUE TITLE
Return empty list when using file input fields as list and no file is selected

### ISSUE THREAD

**Issue by cercos** [MasoniteFramework/masonite#544]
### Describe the bug

Return an empty list when using `<input type="file" name="some_file[]">` and no file is selected.

### Expected behaviour

Return empty list when no file selected

### OS

Linux

### OS version

KDE 5.24.1

### Masonite Version

4.7.0

### Anything else ?

Possible fix could be

_InputBag.py_
```
elif isinstance(value, bytes):
    file = []
    if fields[name].filename:
        file = [UploadedFile(fields[name].filename, value)]
    self.post_data.update(
        {name: file}
    )
```

**Comment by Marlysson** [comment]
Does the correct is a None value?
