### ISSUE TITLE
Update nested validation with index number instead of *

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#548]
### Is your feature request related to a problem?

Currently when there is a validation error when using the `*` nested validations it returns an error like `The users.*.last_name field has duplicate values`. It should show an error like `The users.3.last_name field has duplicate values`

​

`Update`

​
<br />[Tara Task](https://app.tara.ai/masonite-x-inc/*/tasks/42)

**Comment by josephmancuso** [comment]
@girardinsamuel is this possible? we currently hide all the fetching logic behind the dotty code so im not sure its possible to fetch the index of the problem list right?

**Comment by girardinsamuel** [comment]
> we currently hide all the fetching logic behind the dotty code so im not sure its possible to fetch the index of the problem list right?

You're right it's not that simple ! But it's not the only problem, we could mark this a low priority and not easy for now.

**Comment by josephmancuso** [comment]
i found a good way to fix this but not asure if changing validation messages to be clearer is a breaking change or not ..

**Comment by josephmancuso** [comment]
merged this going into the next major version 5.x
