### ISSUE TITLE
Task Scheduling does not return any value when schedule command is run

### ISSUE THREAD

**Issue by Bindukarkee** [MasoniteFramework/masonite#555]
### Describe the bug

> Create a Task using command "python craft task SendInvoice"

> Inside SendInvoice Task, write code to send notification

```python
from masonite.scheduling import Task

from masoniteorm.exceptions import QueryException

from app.notifications.TestNotification import TestNotification

class SendInvoice(Task):
    def handle(self):
        try:
            print("Hello")
            from wsgi import application
            notification = application.make('notification')
            testData = dict()
            testData['name'] = 'Test
            testData['email'] = 'test@test.com'
            testData['subject'] = 'Test Subject'
            notification.send(testData, TestNotification())
            return 'success'
        except QueryException as error:
            print("error")
            return "error"

```

> Register SendInvoice Task inside ServiceProvider as:
```python 
from masonite.providers import Provider

from app.tasks.SendInvoice import SendInvoice

class ServiceProvider(Provider):
    def __init__(self, application):
        self.application = application

    def register(self):
        self.application.make('scheduler').add(
            SendInvoice().every_minute()
        )

    def boot(self):
        pass

```

> Now when I run the command "python craft schedule:run --task SendInvoice", it does not perform any action neither throws any error.

### Expected behaviour

> Command "python craft schedule:run --task SendInvoice" need to print or show any response when it is run

### OS

Linux

### OS version

Ubuntu 18.04

### Browser

Chrome

### Masonite Version

4.6.1

**Comment by girardinsamuel** [comment]
Hi ! You must have an issue with your task because if you try with this simple task
```python
from masonite.scheduling import Task


class TestTask(Task):
    name = "test_task"

    def handle(self):
        print("executed")
```
you should see the `executed` message when running `python craft schedule:run`.

Could you try to just simplify your task to see if it's working ? Then maybe you will be able to debug it.

**Comment by Bindukarkee** [comment]
Hi! I tried it, now it is working. Thank You!
