### ISSUE TITLE
Add logging to views

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#566]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

Need to be able to listen for logging output for views. Can be used for creating a debugging tab for Masonite Debugbar

### Would this be a breaking change ?

- [ ] Yes

**Comment by goophps** [comment]
@girardinsamuel Very much looking forward to your masonite-admin

**Comment by vipermark7** [comment]
Interested in this issue! What exactly needs to be logged, though?

**Comment by girardinsamuel** [comment]
I am thinking of:
- the view name
- the context injected into the view
