### ISSUE TITLE
AMQP driver is incomplete

### ISSUE THREAD

**Issue by yubarajshrestha** [MasoniteFramework/masonite#572]
### Describe the bug

I am not sure if this is bug but we need exchange feature in AMQP Driver which is not being used right now. Also I think we need option to add exchange type as well.

```python
    def publish(self, payload):
        pika = self.get_package_library()
        self.publishing_channel.basic_publish(
            exchange="",
            routing_key=self.options.get("queue"),
            body=pickle.dumps(payload),
            properties=pika.BasicProperties(
                delivery_mode=2,  # make message persistent
            ),
        )
        self.publishing_channel.close()
        self.connection.close()
```

### Expected behaviour

Should be able to use exchange feature and provide types in connection. 

### Steps to reproduce the bug

Easy step is to add exchange type and push exchange messages.

### OS

macOS

### OS version

Monterey 12.3

### Browser

Chrome

### Masonite Version

4.7.1

**Comment by josephmancuso** [comment]
We should be able to do this through the options in the config dict.

**Comment by yubarajshrestha** [comment]
> We should be able to do this through the options in the config dict.

Yea but, we also have to add things in connection type right?

I saw the code but I did not find anything referencing to config.

**Comment by josephmancuso** [comment]
I mean here we need to add support for more options right?

https://github.com/MasoniteFramework/masonite/blob/4.0/src/masonite/drivers/queue/AMQPDriver.py#L72-L81

**Comment by josephmancuso** [comment]
we can do something like:

```
self.publishing_channel.basic_publish(
            exchange=self.options.get("exchange", ""),
            routing_key=self.options.get("queue"),
```

**Comment by yubarajshrestha** [comment]
> we can do something like:
> 
> ```
> self.publishing_channel.basic_publish(
>             exchange=self.options.get("exchange", ""),
>             routing_key=self.options.get("queue"),
> ```

yes also in connection type we need configuration

**Comment by girardinsamuel** [comment]
I added connection options and exchange option (see PR for more info) 😉

**Comment by girardinsamuel** [comment]
@yubarajshrestha does it solve what you wanted to do ?
