### ISSUE TITLE
Fix issue with cookies failing on new projects

### ISSUE THREAD

**Issue by dwedigital** [MasoniteFramework/masonite#573]
### Describe the bug

I have done a clean install of masonite (and had to additionally pip install masonite-orm as a module error was thrown)

Ran `python craft serve` then visited local host to see a TypeError - token must be in bytes.

### Expected behaviour

Some sort of initial landing page loads without errors after clean install

### Screenshots

![image](https://user-images.githubusercontent.com/25953683/161758921-a61e5258-e6d5-4fc2-9844-3d4c86da3211.png)

### OS

macOS

### OS version

Monterey 12.2.1

### Browser

Chrome Version 100.0.4896.60 (Official Build) (arm64)

### Masonite Version

4.6.1

**Comment by girardinsamuel** [comment]
Hi !

Did you run `project install` inside the directory ? (as explained once you have crafted the project with `project start`)

It looks like you did not define the APP_KEY env variable that is required for the project to run. Is a string present in `APP_KEY` variable of your `.env` file ?

**Comment by dwedigital** [comment]
There is. It had a `=` at the end and removed that then new error thrown – Incorrect Padding

From: Samuel Girardin ***@***.***>
Date: Tuesday, 5 April 2022 at 14:18
To: MasoniteFramework/masonite ***@***.***>
Cc: Dave Edwards ***@***.***>, Author ***@***.***>
Subject: Re: [MasoniteFramework/masonite] TypeError - Token must be bytes (Issue #573)

Hi !
Is a string present in APP_KEY variable of your .env file ?

**Comment by girardinsamuel** [comment]
Normally the key should be generated when installing the project.
Did you run project install inside the directory ? (as explained once you have crafted the project with project start)

Else you can still generate a key in your .env file automatically after creating the project with `python craft key`.

**Comment by dwedigital** [comment]
Yes ran `project install` which scaffolded out the whole project and also have run `python craft key` and still the same error

**Comment by girardinsamuel** [comment]
Ok. After running `python craft key` did you have a `.env` file at project root containing 
```
APP_KEY=some-secret-string-123
```
?

**Comment by dwedigital** [comment]
Yes, I have never said the `.env` file never existed. It has always been there since I ran `project install`

**Comment by girardinsamuel** [comment]
The value provided to the crypto module is None so it looks like key is not there. That is why I was checking that your project was setup correctly. For now I cannot reproduce this error.

Could try to run `python craft tinker` and then type `config("application.key")` ? Do you see a key ?

**Comment by dwedigital** [comment]
Sorry, 100% understand why you were checking but it is there and I can get the key within tinker:

```
>>> config("application.key")
'iKx9q3bdylVb-YiwGf0ivNjuoZoZkCWdoWFrer7istQ='
```

Not fussed about sharing as can regenerate and only a local dev at the moment

**Comment by girardinsamuel** [comment]
Okay. Could you post the full stack trace ? (maybe the one you have in terminal will be easier ?)
Thanks 🙏 

(You can hop on Masonite Discord to continue troubleshooting this bug if you prefer https://discord.gg/TwKeFahmPZ 😉. https://discord.com/channels/916859858089828392/960904737908215819)

(Better stack traces and troubleshooting tools are coming to Masonite but not released yet..for now it's a bit tedious)

**Comment by josephmancuso** [comment]
This is due to the cookies issue. Delete your cookies for localhost and it will work. 

It's trying to use the cookies set on a previous Masonite app or a laravel app.

**Comment by dwedigital** [comment]
et voila - solved this issue. Thanks @josephmancuso, turns out pretty simple when you know how!

**Comment by josephmancuso** [comment]
@dwedigital @girardinsamuel this is kind of a known issue I'm just not sure how to solve it. We have to somehow refresh the cookies based on new projects everytime it detects trying to run a new project.

The cookies are saved on the localhost domain so when you run a new app on localhost it tries to use the same cookies as a previous project.

We could somehow detach the app key encryptions from the cookies, or refresh the cookies, or throw a more clear error while in development mode like "Try Deleting your cookies".

**Comment by girardinsamuel** [comment]
Yes we should do something about it and also eventually give a clear message to the user.
With Django there is no problem, so we should address that.

**Comment by josephmancuso** [comment]
I'll reopen issue with a new title to keep track of this

**Comment by goophps** [comment]
@girardinsamuel Looking forward to your masonite-admin

**Comment by goophps** [comment]
Very suspicious, your version numbers are growing too fast.

**Comment by josephmancuso** [comment]
@goophps whats the suspicious part? see the change log. We release new features or fixes every few days. New features you can see here: https://github.com/MasoniteFramework/masonite/releases

Any new features require a bump to the minor version number:

From the SEMVER org:

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

**Comment by os-nikita** [comment]
> Very suspicious, your version numbers are growing too fast.

Quick fixes and frequent releases are a sign of healthy project maintenance. What would be more concerning is a growing list of issues and highly infrequent bug fix releases.

**Comment by os-nikita** [comment]
> @dwedigital @girardinsamuel this is kind of a known issue I'm just not sure how to solve it. We have to somehow refresh the cookies based on new projects everytime it detects trying to run a new project.
> 
> The cookies are saved on the localhost domain so when you run a new app on localhost it tries to use the same cookies as a previous project.
> 
> We could somehow detach the app key encryptions from the cookies, or refresh the cookies, or throw a more clear error while in development mode like "Try Deleting your cookies".

How about looking at the app key? If it's changed when serving, clear cookies on next request.

**Comment by girardinsamuel** [comment]
Yeah why not...

I had this issue a long time ago but now I really did not manage to reproduce it again, so it's hard to work on it.

**Comment by josephmancuso** [comment]
I don't think this is an issue anymore. Cannot replicate this on new installs anymore
