### ISSUE TITLE
Add query string params to url using route or url helper 

### ISSUE THREAD

**Issue by cercos** [MasoniteFramework/masonite#574]
### Is your feature request related to a problem?

Add query string params to url using route or url helper 

### Describe the solution you'd like

Add query string params to url using route or url helper 

### Would this be a breaking change ?

- [ ] Yes

**Comment by girardinsamuel** [comment]
Hi ! I will try to derive some specifications from your feature request:

I think we should able to use it in the following place:

- url helper `url`:
```python
# existing
url("users")  #== http://masonite.app/users
# to add
query_params = {"search": "John Doe" "order": "asc"}
url("users", query_params)  #== http://masonite.app/users/?search=John%2Doe&order=asc
```
- url helper `route`: 
```python
# existing
route("users.profile", {"id": 1})  #== http://masonite.app/users/1/profile/
# to add
query_params = {"admin": True, "mode": 1}
route("users.profile", {"id": 1}, query_params)  #== http://masonite.app/users/1/profile/?admin=true&mode=1
```
- redirect method
```python
# existing
response.redirect(name="users.profile", {"id": 1})
# to add
response.redirect(name="users.profile", {"id": 1}, {"admin": True, "mode": 1})
```
- maybe other places..

What do you think ?

**Comment by cercos** [comment]
Looks good.  Appreciate the fast response.
