### ISSUE TITLE
TestCase's `actingAs()` return type set to None, but should be own class

### ISSUE THREAD

**Issue by os-nikita** [MasoniteFramework/masonite#615]
### Describe the bug

Release `4.11` fixed the lack of a `return self` in several TestCase methods. However, `None` was set as the return type, breaking IDE autocompletion when chaining.

### Expected behaviour

The return type of `actingAs()` and several other methods should be `"TestCase"` to match the other correctly-typed methods. This will allow IDE autocompletion to work with chaining methods.

### Steps to reproduce the bug

* Create a simple HTTP test case
* Instantiate a User model
* Call `self.actingAs(someUserObject).get("/")`
* The IDE won't recognize `.get()` as a valid method.

### Screenshots

<img width="357" alt="image" src="https://user-images.githubusercontent.com/92428260/166478707-a37b1969-065c-4dad-9f79-2dca296f3223.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/92428260/166478951-45b81258-8caf-4dc6-a67e-aacd99de254d.png">

### OS

macOS

### OS version

Monterey 12.3.1

### Masonite Version

4.12.1

**Comment by os-nikita** [comment]
I was somehow on a relatively old version of Masonite, when latest `4.12+` has this fixed already. Not an issue.

**Comment by os-nikita** [comment]
I've updated and re-opened this issue. The relevant problem now is the return type in TestCase.

**Comment by josephmancuso** [comment]
Fixed in https://github.com/MasoniteFramework/masonite/commit/8a6420900b1aeffe7ec2e697284fecb6d565a309
