### ISSUE TITLE
Mailgun Driver does not support `eu` domains in API

### ISSUE THREAD

**Issue by os-nikita** [MasoniteFramework/masonite#627]
### Describe the bug

When adding a new domain in Mailgun, you have the option of specifying EU as the region; US is the default. If the developer does so, then the base API url changes from `https://api.mailgun.net/v3/` to `https://api.eu.mailgun.net/v3/`.

The Masonite Mailgun driver is currently hardcoded to the US endpoint with no way of supporting the EU endpoint without adding a custom driver.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/92428260/168428202-75df1a6b-23e1-4041-beaf-665c6a36c22f.png">

### OS

macOS

### OS version

Monterey 12.3.1

### Masonite Version

4.12.1

**Comment by Marlysson** [comment]
I think that US/EU are values to define the region to mailgun uses in mailing. The domain value ( defined in MAILGUN_DOMAIN ) is the address email that you will use to send the emails.

**Comment by goophps** [comment]
@girardinsamuel Very much looking forward to your masonite-admin
