### ISSUE TITLE
Hi, can I create multi-apps? For example, an admin, an index

### ISSUE THREAD

**Issue by goophps** [MasoniteFramework/masonite#631]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

no

### Would this be a breaking change ?

- [ ] Yes

**Comment by girardinsamuel** [comment]
Hi ! Please join our [Discord community](https://discord.gg/TwKeFahmPZ) to better help you on this subject. It will be easier to discuss what you're trying to achieve here. 

GitHub issues are better suited for feature requests or bug reports. Thanks 🙏.

But to answer your question, there is no limitation in Masonite to do multi-apps, but you will need to explain a bit more what you want to do.
