### ISSUE TITLE
URL paths with `=` in a parameter value result in 404 Not Found in valid routes

### ISSUE THREAD

**Issue by os-nikita** [MasoniteFramework/masonite#633]
### Describe the bug

If you pass an `encrypted` value (such as from Fernet) to a route parameter, the route will not be resolved. I believe this is because the presence of `=` in the value is enough to make the framework think it's a query argument, thus not correctly interpreting the route structure.

This also applies to `base64-encoded` values, which can also contain `=` at the end.

Example of route with encrypted value: `http://localhost:8000/foo/gAAAAABig1By4feqfxl6LLSvkyI7Mve_bPgUKj39IA3-tz94iNQFC5E25VpFoQQxmnXNdyc9brZlbSd1ra8IZUFt22jtJSBi0w==`

Notice the `==` at the end.

### Expected behaviour

The URL should resolve correctly even if the path parameter contains an `=`. A query argument *must* be preceded first with `?` after the path.

### Steps to reproduce the bug

1. Define any route with an argument such as `Route.get('/foo/@bar', ...)`
2. Visit the route to confirm it's working `GET http://localhost:8000/foo/anything`
3. Now visit the route again but just add an `=` at the end, and it will fail `GET http://localhost:8000/foo/anything=`

### OS

macOS

### OS version

Monterey 12.3.1

### Masonite Version

4.12.1

**Comment by girardinsamuel** [comment]
That's an issue indeed ! Thanks for reporting this, we will get to it ASAP.

**Comment by girardinsamuel** [comment]
Actually looking again into the code. You can fix this by specifying a route compiler in your route parameter.
```python
Route.get('/foo/@bar:signed', ...)
```

Available route compilers are:
https://docs.masoniteproject.com/the-basics/routing#route-compilers
and `signed` is handling `=` in urls because its regex is `([\w\-=]+)`

**Comment by os-nikita** [comment]
But that wouldn't solve the issue with base-64, right? 

`base64('foo') == 'Zm9v'`

`base64('foo1') == 'Zm9vMQ=='`

**Comment by os-nikita** [comment]
You're right, that does work, thanks!
