### ISSUE TITLE
Tenants for postgresql schemas

### ISSUE THREAD

**Issue by ystekno** [MasoniteFramework/masonite#642]
### Is your feature request related to a problem?

Is it possible to connect single database to different schemas in postgresql with different **http subfolder** like **django-tenants**?

### Describe the solution you'd like

For example, there are two tenants named demo and apple:
http://localhost:8000/<tenant1>/helloworld -> http://localhost:8000/demo/helloworld
http://localhost:8000/<tenant2>/helloworld -> http://localhost:8000/apple/helloworld

### Would this be a breaking change ?

- [ ] Yes

**Comment by girardinsamuel** [comment]
For the orm part, for now it's not possible to specify the `schema` for postgres. If it was possible, then you would need to 
parse the url to find the name of the schema. And then get the query builder instance by passing the schema to it.

**Comment by josephmancuso** [comment]
I'll take a look into this issue. It is important to be able to set the tenant at the query level. Even globally so you can modify it on each request (which might need a middleware for that?)

**Comment by goophps** [comment]
This is a great feature

**Comment by yubarajshrestha** [comment]
@goophps If we add this feature in postgress, then we have to find similar approach for other databases as well and I think it needs some time to be fixed. Till then here's the package implementation: https://github.com/py-package/masonite-multitenancy

**Comment by josephmancuso** [comment]
This request should use this package https://github.com/py-package/masonite-multitenancy
