### ISSUE TITLE
application instance is not provided to event listeners

### ISSUE THREAD

**Issue by smurf-U** [MasoniteFramework/masonite#651]
### Describe the bug

It gives below error while trying to make custom exception handler using [Catch All Exceptions](https://docs.masoniteproject.com/the-basics/error-handling#catch-all-exceptions)

> Traceback (most recent call last):
  File "/Users/test/workspace_py/test/examples/masonite/mas_venv/lib/python3.9/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/Users/test/workspace_py/test/examples/masonite/mas_venv/lib/python3.9/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/Users/test/workspace_py/test/examples/masonite/mas_venv/lib/python3.9/site-packages/masonite/foundation/Application.py", line 61, in __call__
    return self.response_handler(*args, **kwargs)
  File "/Users/test/workspace_py/test/examples/masonite/mas_venv/lib/python3.9/site-packages/whitenoise/base.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/Users/test/workspace_py/test/examples/masonite/mas_venv/lib/python3.9/site-packages/masonite/foundation/response_handler.py", line 39, in response_handler
    application.make("exception_handler").handle(e)
  File "/Users/test/workspace_py/test/examples/masonite/mas_venv/lib/python3.9/site-packages/masonite/exceptions/ExceptionHandler.py", line 34, in handle
    self.application.make("event").fire(
  File "/Users/test/workspace_py/test/examples/masonite/mas_venv/lib/python3.9/site-packages/masonite/events/Event.py", line 38, in fire
    listener().handle(event, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'application'

### Expected behaviour

While the event is firing, the application object should pass.

### Steps to reproduce the bug

Simply follow the instructions in the [documentation](https://docs.masoniteproject.com/the-basics/error-handling#catch-all-exceptions). The ExceptionListener class is found in another package, which is imported and registered in 'AppProvider.py'.

### OS

macOS

### OS version

Monterey 12.2

### Masonite Version

4.14.1

**Comment by girardinsamuel** [comment]
There is an error in the docs you're right. The event listener does not take the application instance.
It should be:
```python
class SentryListener:

    def handle(self, exception):
        # process the exception with Sentry
        # ...
```

I fixed the docs 😉. Please let me know if it works for you now.

**Comment by smurf-U** [comment]
How can we use the listener to access the instance application?

**Comment by girardinsamuel** [comment]
For now app instance is not provided to listeners when they are registered. I think we should pass the app instance to providers to allow more flexibility. @josephmancuso what's your opinion on this ?

In the meantime, you can do:
```python
class SentryListener:

    def handle(self, exception):
        from wsgi import application
        
        application.make("...")
```

**Comment by josephmancuso** [comment]
Yeah it should be done the way the documentation describes it.

The documentation is saying the put an application parameter in there. 

I was going to fix it last night but my computer died and couldn't find the charger

**Comment by josephmancuso** [comment]
Just going to reopen this issue because it is actually a problem

**Comment by smurf-U** [comment]
I'm able to access application instance but i'm getting other issue to resolve it have to write handle method as below


```python
 def handle(self, exception_type: str, exception: Exception):
        from wsgi import application
        ...
```

**Comment by girardinsamuel** [comment]
> I'm able to access application instance but i'm getting other issue to resolve it have to write handle method as below

You're right, two arguments are provided to the listener. I will fix the docs again. (Type hinting is not mandatory but nice of course 😉).

**Comment by josephmancuso** [comment]
This is good now right? Docs look updated
