### ISSUE TITLE
Route/HTTP middleware after method should execute after exception generate [#tara-label-bug]

### ISSUE THREAD

**Issue by smurf-U** [MasoniteFramework/masonite#659]
### Describe the bug

Create Route or Http Middleware to calculate response time with status code and route info for example:

```python
datas = []
class RouteMiddleware:
    route = {}
    def before(self, request, response):
        route.update({'start': datetime.now(), 'name': request.route.url})
    def after(self, request, response):
        route.update({'end':datetime.now(), 'status': response.get_status()})
        datas.append(route)

```

Register above middleware in `Kernel` in `http_middleware` or `route_middleware.web`, and if one of controller gives exception then it will give `None` value in `status`. Which is not accurate.

### Expected behaviour

`response.get_status()` should return 500 rather then `None`.

### OS

macOS

### OS version

Monterey 12.2

### Masonite Version

4.6.1

**Comment by smurf-U** [comment]
The `after` method of the middleware should be called after the success or error response has been generated.

**Comment by josephmancuso** [comment]
@smurf-U what are you trying to do? Maybe a middleware is not the best place for this

**Comment by smurf-U** [comment]
@josephmancuso Trying to figure out how long it takes to process a route and if it is successful or not.

**Comment by josephmancuso** [comment]
understood thanks
