### ISSUE TITLE
Queue can be hit and miss for emailing 

### ISSUE THREAD

**Issue by dwedigital** [MasoniteFramework/masonite#660]
### Describe the bug

I have got emails that get sent via a job. I am currently using the database driver and jobs always clear out for the jobs table and the worker states they have run succesfully.

The issue is that more often than not the request is never hitting Mailgun and the email is not being sent.

Another thing to check when testing is to change the recipient email between each time the job is run. It felt (not properly tested) the recipient sometmies was not updating and was sending to a previous email.

```
from masonite.queues import Queueable
from masonite.facades import Mail
from app.mailables.Test import Test


class SendTestEmail(Queueable):
    def __init__(self, person: str) -> None:
        self.person = person
    def handle(self):
        res =  Mail.mailable(Test().to(self.person)).send()
        print(res.status_code)
```

```
from masonite.mail import Mailable


class Test(Mailable):
    def build(self):
        return (
            self.subject("Masonite 4")
            .from_("admin@gmail.com")
            .text("Hello from Masonite!")
            .html("<h1>Hello from Masonite!</h1>")
        )
```

Calling it from the controller: `queue.push(SendTestEmail("dave@dwedigital.com"))`

### Expected behaviour

The emails should be sent everytime without fail as they do when calling `mail.mailable()` directly in the controller instead of using the queue

### OS

macOS

### OS version

12.2.1

### Masonite Version

4.14.3

### Anything else ?

_No response_<br />[Tara Task](https://app.tara.ai/masonite-x-inc/*/tasks/66)

**Comment by dwedigital** [comment]
After further testing it seems restarting the server and queue worker fixes the problem for a period of time

**Comment by os-nikita** [comment]
This sounds like the "singleton" issue with Python that I ran into with Auth. There may be something not being reset between  requests or jobs on the worker.

@dwedigital You could try replicating it through `craft queue:work` locally and keep it running, listening to jobs from the db, then in a separate process attempt sending to one email, and then a different email. Will both deliver to the correct address?

**Comment by dwedigital** [comment]
I have tried that and it works however after a while it can stop. As stated, restarting the queue worker fixes it but just not sure how must testing it has gone through under more load and a longer period of time

**Comment by josephmancuso** [comment]
Going to close. Can reopen if experience this again
