### ISSUE TITLE
Official M3 Providers ported to M4

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/masonite#675]
### Is your feature request related to a problem?

Not really

### What do we currently have to do now?

Write your own Provider or attempt to port the M3 Providers to work with M4 

### Describe the solution you'd like

I would like to be able to use the official third party providers that M3 has available in M4
These include but are not limited to:
masonite-debugbar
masoinite-billing
masonite-logging (which is already under discussion in #663 )

To get the debugbar and billing Providers working would be amazing but im not sure how to start this?
The code for all these Providers is under active developemnt for M3 so do we start a new version of each for M4 which will eventually become the default?  

I would be happy to help bring these into use with M4 but am not sure where to start?

### Would this be a breaking change ?

- [ ] Yes

**Comment by josephmancuso** [comment]
masonite-debugbar only works with M4 🤔

**Comment by circulon** [comment]
@josephmancuso 
> masonite-debugbar only works with M4 🤔

Ok this is weird and no it does not work with M4 at all
ie it cannot even be enabled and produces the exact same errors  as the Billing and logging providers.
So I created an issue on Masonite-debugbar which shows this issue  with M4
https://github.com/MasoniteFramework/debugbar/issues/38

**Comment by josephmancuso** [comment]
The billing package is planned for a rewrite and the logging feature is open in #663 so i'll close this one
