### ISSUE TITLE
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named TestController has been found in ['app.controllers.api']

### ISSUE THREAD

**Issue by Antony-Jia** [MasoniteFramework/masonite#676]
### Describe the bug

When I change API Controller name it happened. When I change name to original it still exit.
When I revert the code, the bug is missing.

### Expected behaviour

How to Generate API Controller?  The Only way is the command python craft controller api/UsersController -a?

### Screenshots

![image](https://user-images.githubusercontent.com/58219593/174746376-a4168681-8247-40c5-bb0d-0484acb7574c.png)
![image](https://user-images.githubusercontent.com/58219593/174746434-dc05f5a4-609e-476f-b0ad-575ab6921e16.png)
![image](https://user-images.githubusercontent.com/58219593/174746642-c0c685a2-b633-49b4-8574-527591ef8ccf.png)
![image](https://user-images.githubusercontent.com/58219593/174746695-ea53680f-2370-4183-8eb1-c071a8899f08.png)
![image](https://user-images.githubusercontent.com/58219593/174747316-90b93939-147a-4a5f-b58d-ed141fa67fbf.png)

### OS

Windows

### OS version

Window 10

### Masonite Version

4.15

**Comment by Antony-Jia** [comment]
this is compile issue. i'd fix it

**Comment by rob-hills** [comment]
I am getting the same error message today using the current Masonite in PyPi (4.20.2).
Has this been fixed in 4.20.3 which is in GitHub but not PyPi?
