### ISSUE TITLE
Masonite has poor performance when I make a lot of calls to the cache.

### ISSUE THREAD

**Issue by goophps** [MasoniteFramework/masonite#678]
### Describe the bug

Masonite has poor performance when I make a lot of calls to the cache. 

I looked at the code here and thought that the singleton pattern was not used. Later I found out that already uses the singleton pattern.

filename：site-packages/masonite/cache/drivers/RedisDriver.py
line：21
code：
        if not self.connection:
            self.connection = redis.StrictRedis(
                host=self.options.get("host"),
                port=self.options.get("port"),
                password=self.options.get("password"),
                decode_responses=True,
            )

This function already uses the singleton pattern. So in the end, I didn't find the reason for the poor performance.
def get_driver(self, name=None):

### Screenshots

this code：time cost: 0.90 seconds
![image](https://user-images.githubusercontent.com/49714224/174901699-ce5f659d-eebb-4822-9ec0-05fb00e84255.png)

this code：time cost: 2.76 seconds
![image](https://user-images.githubusercontent.com/49714224/174901608-1ff8c420-6d4d-417b-b555-be493ea761bc.png)

### OS

Linux

### OS version

deepin

### Masonite Version

4.15.0

**Comment by josephmancuso** [comment]
@circulon can we save the open connection and just handle it not being able to connect when it sends and gets the data?

It's probably slow because it has to reopen and close the connection everytime

**Comment by circulon** [comment]
> @circulon can we save the open connection and just handle it not being able to connect when it sends and gets the data?
> 
> It's probably slow because it has to reopen and close the connection everytime

@josephmancuso  
I would say yes.  
Using a singleton pattern to hold the connection once its been setup  would make sense and remove the reconnection overhead
 But it would require testing

Will see if I have some time over the next week to try this.

**Comment by circulon** [comment]
@goophps @josephmancuso 

I cannot replicate @goophps  results.

System:
27" iMac : 4 GHz Quad-Core Intel Core i7 (late 2015)
Mac OS 12.4
Memory: 40 GB 1867 MHz DDR3
Storage: 1Tb Samsung SSD 860 Pro

Testing setup:
- Brand new masonite project and venv.
- `test_redis.py` as per @goophps  code
  - run with `python test_redis.py`
- `WelcomeController` as per @goophps code
  - run with `python craft serve -p 8000` 
- running Redis 6.2.6 64 bit on localhost 

My result with 10000 iterations
- test_redis.py
  time cost = 0.53 seconds
- running "python craft serve -p 8000" and hitting the http://127.0.0.1/8000
  time cost = 0.38 seconds
 
Increase iterations to 100000
- test_redis.py
  time cost = 5.24 seconds
- running "python craft serve -p 8000" and hitting the root url
  time cost = 3.28 seconds

So based on my basic testing I would say that the connection is indeed being cached and reused as expected which increases performance by ~50% on average response time in my testing.
This is just my subjective testing and should not be taken as conclusive.

Please Note : I am in no way an expert on  using Redis so I would recommend  additional testing by others to confirm my findings.

**Comment by circulon** [comment]
@josephmancuso 

Reviewing how the Cache works, there is a possibility that performance could be increased further by "caching" (no pun intended ;)  the values gathered from the particular driver in the same way that the Session component does.  
This would reduce hits on the Cache (Driver) if the value already exists.
As it stands the Redis Cache driver hits Redis twice if the value exists (one for .has and one for .get) so this could be reduced to 0 if all the data the cache holds was loaded on initial check for a value and then pulled from the "internal" cache on subsequent .get() requests.

The only consideration would be memory consumption for initial loading if the cache store holds a large amount of items/content.
Searching for values based on the key prefix (like the Redis Session Diver does) might alleviate this issue.

I'm just considering additional options if this performance issue turns out to be a real problem.

**Comment by josephmancuso** [comment]
@circulon thanks good to know. What's your thoughts on this issue? #680

**Comment by circulon** [comment]
@josephmancuso 

I think we have a problem here and this should be reopened.

After looking at the code @goophps provided I realised the the key was never being "set" so the `.get()` in the RedisDriver always returned `None` ie incurring 1 hit to redis for the `.has()`

so I altered the test to look like this and set / clear the key before and after the timing check.
Note: the `.put()` & `.forger()` are replaced with the redis module `.set()` & `.delete()` respectively in the `test_redis.py` 
```python
        cache.put("foo", "bar")
        start = time.time()
        for x in range(100000):
            cache.get("foo")
        end = time.time()
        msg = "time cost = {:.2f} seconds".format(end - start)
        print(msg)
        cache.forget("foo")
```

The results showed approximately the same as the ones @goophps  noted
10000 iterations:
- test_redis.py
  - time cost = 0.57 seconds
- WelcomeController
  - time cost = 1.62 seconds
 
100000 Iterations
- test_redis.py
  - time cost = 5.69 seconds
- WelcomeController
  - time cost = 15.59 seconds

This is quite a significant performance hit ;(

I'm going to start looking into a solution for this and will submit a PR or at least provide further info in this issue if I get stuck.

**Comment by josephmancuso** [comment]
Ok thanks for checking let me know if you need something from me

**Comment by circulon** [comment]
@josephmancuso 

We have 2 scenarios here that will offer performance boosts

Scenario 1: Cache only keys from Store
10000 iterations:
- test_redis.py
   - time cost = 0.56 seconds
 - WelcomeController
   - time cost = 0.92 seconds
 
100000 Iterations:
- test_redis.py
   - time cost = 5.57 seconds
 - WelcomeController
   - time cost = 9.34 seconds
 
Pros : 
- Keys are all cached internally so lookup is fast
Cons:
- still slower than the direct method (~40% slower), but stll better than the ~65% slower we currently have
- items always pulled from the store (if it exists)   
   
Scenario 2 : Cache both the keys and values from the store internally in the driver class
10000 iterations:
- test_redis.py
   - time cost = 0.56 seconds
 - WelcomeController
   - time cost = 0.16 seconds
 
100000 Iterations:
- test_redis.py
   - time cost = 5.57 seconds
 - WelcomeController
   - time cost = 1.63  seconds
 
Pros : 
- ~340% - 350% faster access
- Keys and values are all cached internally so lookup after initial loading   y incurs 0 hits to the store on retrieval 
Cons:
- Large numbers of (or large values) may increase the memory footprint  


These are just my initial findings.
If there is a lesser likelyhood of large numbers of cache items (or large objects) then I would recommend Scenario 2 for a significan boost in performance.
Additionally I would recommend looking at the other cache drivers too as Scenarion 2 could benefit at least the memcached store to start with.
