### ISSUE TITLE
Multiple drivers - .get() with default value will produce data inconsistencies

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/masonite#685]
### Describe the bug

Using a `default` value in .get() does not actually store the default value.
This means that updating the key using methods that require the key to have an existing. 
eg `.increment()`, `.decrement()` 

This exists across multiple drivers including but not limited to 
- All Cache Drivers
- Redis Session Driver
- There might be others but I havent looked that hard yet ;)

### Expected behaviour

When a `default` value is used the key should be set in the `store` with that default value if the `key` is not already set

### Steps to reproduce the bug

Many Drivers (all Cache drivers ata minimum) use  code similar to the following:
```python
   def get(self, key, default=None, **options):
        if not self.has(key):
            return default

        return self.get_value(
            self.get_connection().get(f"{self.get_name()}_cache_{key}")
        )
```
This will produce data inconsistencies when a `default` value is used

Scenario:
assume all config is setup for a given Cache driver 
```python
# cache key "foo" has not yet been set
foo_var = cache.get("foo", 3) # expect that "foo" is now set to 3 in the store
print(f"foo_var: {foo_var}") # "foo_var: 3"
# get the "foo" var again 
new_foo_var = cache.get("foo") # expected value = 3
print(f"new_foo_var: {new_foo_var}") # "foo_var: "

inc_var = cache.increment("foo", 7)
print(f"inc_var: {inc_var}") # "inc_var: 7"
```
Expected value of key "foo" is 10
This is because the key "foo" is never set if a default value is used.
 

### OS

macOS

### OS version

OS X Monterey 12.4

### Masonite Version

4.6.1

**Comment by goophps** [comment]
This is not a bug, the purpose of the default value is that when the return value is empty, the default value is returned. We can't set default values into Redis, don't do that.

**Comment by goophps** [comment]
Also like this, dict.get(key, default=None), this default value will not update your dictionary.

**Comment by circulon** [comment]
> This is not a bug, the purpose of the default value is that when the return value is empty, the default value is returned. We can't set default values into Redis, don't do that.

@goophps  so how do you propose to alleviate the scenario as I oultined above?  
Just saying "dont do that" does not provide any meaningful discussion on this issue.

Additionally as this is about  persistent store drivers and the values should be retained,  why not set the default value as provided in order to stop data inconsistencies?

In any case this has been partially addressed (for Redis Cache driver atleast) in PR #686

**Comment by goophps** [comment]
If you need to do this, you can encapsulate a function yourself, and if there is no value, set the value in it.

**Comment by josephmancuso** [comment]
I would actually tend to agree with @goophps.

Its not good to store a default like that when getting.

To solve the scenario of:

> expect that "foo" is now set to 3 in the store

Is, in my opinion, an incorrect expectation. 

Now if you want to make a new method like `get_or_set("foo", 3)` which would do your behavior I think that would be better. But I don't want to be storing defaults when using the get method

**Comment by goophps** [comment]
![image](https://user-images.githubusercontent.com/49714224/177365320-b61c87a0-d306-42bb-a1bb-db5dd0a6261d.png)

See if this works.

**Comment by josephmancuso** [comment]
I'd be open to a method like that
