### ISSUE TITLE
ModuleNotFoundError: No module named 'masonite'

### ISSUE THREAD

**Issue by filipprober** [MasoniteFramework/masonite#689]
### Describe the bug

Hey guys,

maybe it's not Masonite specific, but when I use the zsh, this error comes up:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/65421448/177007890-7a439228-cfd5-445a-9d0c-22ddfba576d7.png">

My requirements.txt file looks like this:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/65421448/177007974-7c309a46-9f2d-471f-a0af-9511d53a4f54.png">

The interesting part is when I use bash, it works as it should:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/65421448/177008081-60b49bfd-08c2-426b-8c03-c8a1e68dddc0.png">

(Btw, it's the same project folder)
Has anyone had this problem and know how to solve it?
Installed Python version: v3.9.13

Thanks!

### OS

macOS

### OS version

Monterey 12.4

### Masonite Version

4.6.1

**Comment by josephmancuso** [comment]
Looks like the first screenshot you didn't have the virtual environment active? In the second screenshot I can see the `(masonite)` env active

**Comment by filipprober** [comment]
Sorry, forgot to activate the virtual environment but unfortunately it does not work :(
<img width="772" alt="image" src="https://user-images.githubusercontent.com/65421448/177008596-9e9affd4-1a60-4b22-a74c-75e55ff5cc81.png">

**Comment by josephmancuso** [comment]
oh its probably because the virtual environment is the same name as masonite. Need to name it something else like `masonitevenv`

**Comment by filipprober** [comment]
Okey, I fixed it by running the following command outside the virtual environment:
`pip3 install masonite`

It works as it should. Thanks!
<img width="728" alt="image" src="https://user-images.githubusercontent.com/65421448/177009046-6e459133-d525-488d-8198-96c796923f53.png">
