### ISSUE TITLE
Auth routes (GET) return Not Found even though they are valid routes

### ISSUE THREAD

**Issue by horsehead97** [MasoniteFramework/masonite#692]
### Describe the bug

register and login routes produce a route not found exception
GET /register: 404 Not Found
GET /login: 404 Not Found

### Expected behaviour

register and login routes should bring up a register or login page

### Steps to reproduce the bug

Install masonite.
Run migration
add these 2 lines to web.py:
from masonite.authentication import Auth
ROUTES += Auth.routes()

### OS

Linux

### OS version

Ubuntu

### Browser

Brave

### Masonite Version

4.6.1

### Anything else ?

python craft routes:list shows the routes, yet all the Auth routes (home,login,register) return a 404 Not Found

**Comment by josephmancuso** [comment]
Please update to latest version of Masonite and see if that fixes the issue. 4.6.1 is pretty far behind

**Comment by josephmancuso** [comment]
Will reopen if we get more information
