### ISSUE TITLE
Question: how to render a widget view in a view

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/masonite#697]
### Is your feature request related to a problem?

No

### What do we currently have to do now?

Unknown

### Describe the solution you'd like

I would like to render Widgets (html fragment code or a `View` subclass) within a view template for modularity and reusability.

Currently generating the widget fragment like this
```python
        crumbs = [
            {"label": "List", "route": "list.index"}
        ]
        breadcrumbs = view.render('widgets.breadcrumbs', {"breadcrumbs": crumbs}).get_content()
        return view.render("index", compact(breadcrumbs) )
  ```

There doesnt seem to be a `raw` View filter which would facilitate this.
I'm currently working on the premise that I have to render the Widget as a string then pass it into the view as a var where I place it and do something like this:
`{{ breadcrumbs_widget | raw }}`  which renders the string as the generated raw html.

### Describe alternatives you've considered

An alternative to the `raw` method would be to create a Filter that renders the var into  widget html but that feels a bit wrong.

ie in controller:
```python
        breadcrumbs = [
            {"label": "List", "route": "list.index"}
        ]
        return view.render("index", compact(breadcrumbs))
  ```
in the View template:
```python
{{ breadcrumbs|widget_crumbs }}
```

### Would this be a breaking change ?

- [ ] Yes

**Comment by josephmancuso** [comment]
I think you're trying to find the `include` tag

https://jinja.palletsprojects.com/en/3.1.x/templates/?highlight=include#include
