### ISSUE TITLE
Broken redirects to external url

### ISSUE THREAD

**Issue by racerthunder** [MasoniteFramework/masonite#714]
### Describe the bug

version: 4.16.4

there is no easy way to make a redirect the external url inside controller, ex.

`self.response.redirect('https://google.com')`

the "add_query_params" function expects only inner url and returns back empty string. 

current workaround is to add header manually:

```
    def home(self, view: View):
        url = 'https://google.com'
        res = self.response.redirect(url)
        res.header_bag.add(Header("Location", url))
        return res
```

### OS

macOS

### OS version

Monterey 12

### Masonite Version

4.16.4

**Comment by girardinsamuel** [comment]
Actually it should possible to do it using `self.response.redirect(location="https://google.com")`. I will check if it's working on my side.

**Comment by gabefair** [comment]
Also reported in #768 

Today in V4, 'Controller' object "self" has no attribute 'response'.

**Comment by samuelmukoti** [comment]
Is there any update on this issue?

**Comment by josephmancuso** [comment]
@eaguad1337 you found something with this right? i remember we talked about why this was happening but dont remember what we came up with

**Comment by eaguad1337** [comment]
I swear I fixed it. Did you reproduce the issue?

**Comment by josephmancuso** [comment]
i think this was actually fixed. i see commits explainingthe "workaround" in the codebase after the reported issue which is why i couldnt replicate this when i tried
