### ISSUE TITLE
Alternate Authorization mechanisms

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/masonite#716]
### Is your feature request related to a problem?

Not really

### What do we currently have to do now?

Not really sure how to address this as `Gate` in the only method of Authorization and cannot be disabled / overridden  to allow other Authorization flows to be used.

 

### Describe the solution you'd like

I would like to use a different Authorization flow other than Gates & Policies.
In my case I would like to use `Casbin` as an Authorization provider as this can be then linked to a multitude of different rule and policy stores that Casbin reconises (ie file, db, etc)

As there is no "config" setup for Authorization like there is for Authentication there is no easy way to change Authorization flows.  

Possibly having the `AuthorizesRequest` class lookup the `driver` flow from the config `authorization`

 

### Describe alternatives you've considered

Cannot find any as `AuthorizesRequest`  class hardcodes using the `Gate` as the only authorization flow.

### Would this be a breaking change ?

- [ ] Yes

### Anything else ?

If done properly this would not be a breaking change as internal config defaults could be set to use the `Gate`

**Comment by josephmancuso** [comment]
> Not really sure how to address this as Gate in the only method of Authorization and cannot be disabled / overridden to allow other Authorization flows to be used.

Gates are not used out of the box so if you don't use gates then you don't have to disable / override them

**Comment by josephmancuso** [comment]
I think you just have to build it into your application as a custom class and custom config. 

Is this issue requesting we build a Casbin driver for Masonite? I'm kind of confused on what this ticket is for

**Comment by circulon** [comment]
@josephmancuso 
> Gates are not used out of the box so if you don't use gates then you don't have to disable / override them

Yeah I understand that if there are no defined rules they are not used. 
My point was that even if not defined Gates are still hardcoded into the Request flow.
No issue there, just pointing it out.



> I think you just have to build it into your application as a custom class and custom config.

Yeah that is not a problem and have already done that exact thing for a custom provider. 


> Is this issue requesting we build a Casbin driver for Masonite? I'm kind of confused on what this ticket is for

No I'm not asking for a Casbin provider.  I am hoping  to add it to Masonite by building one.  

I am just stuck on how to get this alternate Authorization Provider into the Request flow in the same way Gates are currently used.
Maybe implement as a middleware? But that feel counter intuitive considering there is already an AuthorizationProvider

Apologies for the confusing question

**Comment by girardinsamuel** [comment]
>  My point was that even if not defined Gates are still hardcoded into the Request flow.

Hmm yes because of this 
```python
# request.py
class Request(ValidatesRequest, AuthorizesRequest):
```
you're right.

@josephmancuso We have to think about it

**Comment by girardinsamuel** [comment]
Actually no, here `AuthorizesRequest` just adds a handy shortcut to test gate access from the request object. So it's not really bundled into core. If you want to check permissions you still have to put the checks somewhere: either in Controller or in a Middleware.

So it would be the same for your custom system.

Example:

```python
from masonite.facades import Gate
from masonite.middlewares import Middleware

class AuthorizeMiddleware(Middleware):
    def before(self, request, _, guard):
        Gate.authorize("display-admin")
        # or request.authorize("display-admin")
        return request

    def after(self, request, _, __):
        return request
```

@circulon I would be happy to discuss it with you further on Discord if you need help. As I don't see an issue here, I will close this issue.

**Comment by circulon** [comment]
@girardinsamuel 
>  you still have to put the checks somewhere: either in Controller or in a Middleware.
> 
> So it would be the same for your custom system.
> 

As it turns out that is exactly what I did a couple of days ago and have not had a chance to reply and confirm.  
Using a Route Middleware gives a lot of flexibility ie I can add permissions conrtol to specific controllers 

For those that may be looking for an alternative to Gates this is what I did.

As I'm using Casbin for centralised permissions (RBAC) I put it all together like this
- Added a `CasbinAuthorize` component class which holds the enforcer instance and other custom methods I need
-  Added a `CasbinProvider`  which binds the `CasbinAuthorize` instance (with its config) into the `applicatopm`
- Added a `AuthorizeMiddleware` which gets the `CasbinAuthorize` instance from the app binding 
- - in the `before` method of the `AuthorizeMiddleware` 
- - - get the role of the logged in User  (ie user, manager, admin, etc)
- - - get the route name (eg products.show, products.update, etc) which is is being accessed and is available from the `request` object via `request.get_route().get_name()` method
- - - define the logic for what to do if the role is not authorised to access the route ie raise a `AuthorizationException` exception 
-  Add the `AuthorizeMiddleware` to the `route_middleware` in the `Kernel.py` named as `authorize`
- Finally add the `authorize` middleware to any controller where my RBAC permissions are required

By doing it like this, now all I have to do to get full RBAC on a given controllers and its actions is
1 add a couple of lines to the Casbin policy defining the role and the endoints it can access for the controller 
2 add the named `authorize` middleware to the  RouteGroup attached to the controller 

I put this here for reference purposes if anyone else is considering using Casbin (or any other third party Authorization for that matter) as a way forward
