### ISSUE TITLE
SoftDeletesMixin doesn't force_delete 

### ISSUE THREAD

**Issue by cercos** [MasoniteFramework/masonite#720]
### Describe the bug

The force_delete() method is not deleting record.

### OS

Linux

### OS version

Linux

### Browser

Edge

### Masonite Version

4.6.1

### Anything else ?

Changing the return value on the _force_delete() method on SoftDeleteScope shown below makes it work by I am unsure if there is any internal functionality that is lost by the change.

Old return:
`return builder.remove_global_scope(self).set_action("delete")`

New return:
`return builder.remove_global_scope(self).delete(self)`

**Comment by girardinsamuel** [comment]
Thanks for reporting this ! Can you move this bug report to Masonite ORM repo ? https://github.com/MasoniteFramework/orm/issues
It belongs here 😉 

We will fix this ASAP.

**Comment by cercos** [comment]
Yeah sorry about that, forgot it was a separate repo
