### ISSUE TITLE
masoniteproject.com domain issues

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/masonite#753]
### Describe the bug

It appears that the masoniteproject.com and related subdomains are no longer responding. This includes
https://docs.masoniteproject.com/ and https://orm.masoniteproject.com/ 

I mentioned this on the discord server, but also reporting it here.

### OS

Linux

### OS version

Ubuntu

### Masonite Version

all

**Comment by Leon0824** [comment]
It's now live.
