### ISSUE TITLE
Object of type Decimal is not JSON serializable

### ISSUE THREAD

**Issue by c3hb** [MasoniteFramework/masonite#757]
### Describe the bug

I have a decimal column on my my db table and I'm trying to return the model as json. `.serialize()` successfully converts the model to a `dict`, but looks like the json encoder fails.

An interesting aside is the built in decimal cast used in `__casts__` successfully converts the decimal column to a string in the json.

### Expected behaviour

Output a decimal number in the json rather than throw an error (and not require casting a decimal column as a decimal for it to run)
```json
{
    "amount": 10.00
}
```

Maybe the built in decimal cast should return the same result as well instead of a string representation.

### OS

macOS

### OS version

13.3

### Masonite Version

4.17.4

**Comment by Charlton-A** [comment]
Hi @ChristopherBrownie . From your description I assume you want to have the value represented as `float`  . You can use cast on your model to convert it to a float instead of string ` __casts__ = { "amount": "float"}`

**Comment by c3hb** [comment]
Found that in order to retain precision in json it needs to be a string, so the existing behavior is correct, sorry about that and thanks for the feedback.
