### ISSUE TITLE
Add Route.any facade

### ISSUE THREAD

**Issue by eaguad1337** [MasoniteFramework/masonite#772]
### Is your feature request related to a problem?

No

### What do we currently have to do now?

If you want to define a route that accepts any http method, you need to do something like this:

`Route.match((“GET”, “POST”, “PUT”, “PATCH”, “DELETE”), “/any”, “WelcomeController@any”)`

### Describe the solution you'd like

It would be nice to have a short version of match like this:

`Route.any(“/any”, “WelcomeController@any”)`

### Would this be a breaking change ?

- [ ] Yes

**Comment by josephmancuso** [comment]
this was merged
