### ISSUE TITLE
Cannot open my blog web page

### ISSUE THREAD

**Issue by JustSirDave** [MasoniteFramework/masonite#785]
### Describe the bug

Trouble importing controller!
> No <class 'masonite.controllers.Controller.Controller'> named Controller has been found in ['app.controllers']

### Expected behaviour

I am expecting to have a the required web page to open and not giving me error 404

### OS

Windows

### OS version

windows 10

### Browser

chrome

### Masonite Version

4.6.1

**Comment by josephmancuso** [comment]
i need code snippets or something to work on. cant just work on an error with no way to replicate it.

will reopen if new info is posted
