### ISSUE TITLE
Invalid requirement (cryptography (>=2.3<3.5)) found in masonite-3.0.13 dependencies, skipping

### ISSUE THREAD

**Issue by jteasley1113** [MasoniteFramework/masonite#790]
### Describe the bug

I am using Python poetry to install a set of python libraries and am getting this error which seems to be referencing a requirements.txt file within the Masonite 3.0.13 framework. I've tried specifying my cryptography package to a different version, however, this does not affect the masonite dependencies. Perhaps there is a way to override the masonite-3.0.13 dependencies with my own? Please let me know if this is something that needs to be updated within my own python packages or if Masonite is responsible. 

### Steps to reproduce the bug

After running
$ poetry init

Place the following code in project.toml:
[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.13"
masonite = "^3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

Then run
$ poetry install

### OS

Linux

### OS version

Mint

### Masonite Version

3.0.13

**Comment by josephmancuso** [comment]
what version of cryptography are you trying to use?

**Comment by jteasley1113** [comment]
It was originally on 2.7 so I tried bumping it up to 35.0.0, however, even without specifying the package (exactly how the project.toml is shown) it gives me the error.

**Comment by josephmancuso** [comment]
Masonite 3 isnt supported anymore. I'm not going to push a new release of an old version of Masonite. consider upgrading to Masonite 4 if you really need cryptography 35
