### ISSUE TITLE
Undefined name 'view' in WelcomeController.py

### ISSUE THREAD

**Issue by cclauss** [MasoniteFramework/masonite#90]
flake8 testing of https://github.com/MasoniteFramework/masonite on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./app/http/controllers/WelcomeController.py:8:16: F821 undefined name 'view'
        return view('welcome', {'app': Application})
               ^
1     F821 undefined name 'view'
1
```

**Comment by josephmancuso** [comment]
yeah so Masonite has this concept of "helper functions" which are loaded into the application via the `HelpersProvider` in the `PROVIDERS` list inside `config/providers.py`

You do not have to use them but they are there if you want them. What you want instead is to resolve the `View` from the container:

example:

```
def show(self, View, Application):
    return View('welcome', {'app': Application})
```

**Comment by cclauss** [comment]
Then I would suggest that you please add __global view__ to the line above this one to make that assumption clear to the reader.

**Comment by josephmancuso** [comment]
I honestly think that makes the code a little messy for no real benefit but I'm open to suggestion. 

It's sort of clear what it does and I think it's fairly clear in the docs about how helper functions work like in the tutorial and people can remove them if they don't like them in favor of explicitly importing a class or resolving from the container. If developers want to remove them like the code example above or if they are running through flake8 then they should not use them at all.

**Comment by josephmancuso** [comment]
You can throw the global on top of your own project so it makes more sense to you but Masonite only really has 2 helper functions that people use:

```
def show(self):
    request()
    # and
    view()
```

If you don't like the helper functions you should remove them in favor of explicit imports and annotation resolving:

```
from masonite.view import View
from masonite.request import Request

def show(self, view: View, request: Request):
    request.input(..)
    return view.render('welcome', {..})
```
