### ISSUE TITLE
Better/simplified form rendering

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/masonite#91]
Masonite handles forms like this, now:
`<form action="/post/{{ post.id }}/update" action="POST"></form>
`
It would be pretty to improve form rendering & form submission (validation).
Thanks.

**Comment by josephmancuso** [comment]
the forms and validation now is a little more "manual" so hopefully our forms package will tie everything together.

**Comment by nioperas06** [comment]
Validation looks good! The essential is there. The other validation rules will come as one goes along 😄 .

**Comment by josephmancuso** [comment]
https://github.com/MasoniteFramework/forms
