### ISSUE TITLE
craft command throws SSL and URLopen errors

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#92]
found a few issues in the craft command "new" ,

The first issue is that it's not handling python3 and python2 correctly. There should be no `from .commands import NewCommand` it should be `from masonite_cli.commands import NewCommand`

Next, the exception handling for urllib is also wrong. It should look something like this instead:

```
try:
    # Python3 logic
except ImportError:
    # Python2 logic
except Exception as e:
    raise e
```

great first issue. This fix should be inside the `masoniteframework/craft` repo. Please comment if you want to fix this issue

**Comment by nioperas06** [comment]
✋ Got it!

**Comment by nioperas06** [comment]
Should I do the same thing(add from masonite_cli...) with this lines?
```
from .commands.InstallCommand import InstallCommand
from .commands.PackageCommand import PackageCommand
```

**Comment by josephmancuso** [comment]
Update masonite-cli


On Jun 21, 2018 at 6:55 PM, <Junior Gantin <notifications@github.com>>
wrote:

Should I do the same thing(add from masonite_cli...) with this lines?

from .commands.InstallCommand import InstallCommand
from .commands.PackageCommand import PackageCommand

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MasoniteFramework/masonite/issues/92#issuecomment-399268621>,
or mute the thread

**Comment by josephmancuso** [comment]
I updated masonite just never pushed to the repo. Will do it tonight

**Comment by josephmancuso** [comment]
Sorry lol. I had a few minutes and decided to just finish this issue. Hey be sure to get into the slack channel :) http://slack.masoniteproject.com
