### ISSUE TITLE
migration error using sqlite

### ISSUE THREAD

**Issue by jjgalvez** [MasoniteFramework/masonite#93]
I am going through the blog example using sqlite as the database, When I run craft migrate I get the following error 
`[TypeError]                                              
  'host' is an invalid keyword argument for this function `

**Comment by josephmancuso** [comment]
what does your database configuration look like? Please omit any secret keys

**Comment by jjgalvez** [comment]
DB_DRIVER=sqlite
DB_DATABASE=blog.db
DB_USERNAME=root
DB_PASSWORD=root

**Comment by josephmancuso** [comment]
what if you out in a DB_HOST? Maybe that's missing?

**Comment by josephmancuso** [comment]
try setting it to something like `localhost:8000` or something local?

**Comment by jjgalvez** [comment]
changed it to both localhost and localhost:8000, neither work, same error

**Comment by josephmancuso** [comment]
can you show me whats in your config/database.py file?

**Comment by jjgalvez** [comment]
That was was it! I was following the blog tutorial and it never mentioned anything about editing that file. Anyway I commented out host, user, and password, which are not needed for sqlite.

Thanks

**Comment by josephmancuso** [comment]
Awesome. I'll update the documentation!

**Comment by josephmancuso** [comment]
wait was it in the official docs or an online blog tutorial?

**Comment by jjgalvez** [comment]
the official docs
https://docs.masoniteproject.com/creating-your-first-blog
