### ISSUE TITLE
Fix install issues with craft install command

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite#94]
So there is a slight issue with the craft install command. Sometimes you get a permission issue when installing dependencies. I think it's because of how Masonite is first installed. 

I think installing `masonite-cli` as a user will require installing the dependencies as a user.

So what we need is a command like this:

    $ craft install --user

which will run `pip3 install --user -r requirements.txt`.

We just need to add a flag to the command and then append that flag.

### Steps

This really just entails adding an option to the command:

```
....
    install
        {--u|user : Install dependencies for the current user only}
    """
```

and then in the code so something like:

```python
....
if self.option('user'):
    user = '--user'
else:
    user = ''

call(["pip3", "install", "{}".format(user), "-r", "requirements.txt"])
....
```

this will be in the `Masoniteframework/craft` repository

**Comment by josephmancuso** [comment]
@nioperas06 Do you want to take this one? This should be really simple. Then you'll be a contributor!

**Comment by MichaelYusko** [comment]
@josephmancuso If  @nioperas06 won't take the ticket, I'll happy to work on. So it would be a cool start, because I planning to contribute into the `core` package.

**Comment by nioperas06** [comment]
Yeah, @MichaelYusko you can go for it. 👍 I'll find something to do 😄

**Comment by josephmancuso** [comment]
@MichaelYusko Great!. Be sure to join the slack channel if you have any questions: http://slack.masoniteproject.com

**Comment by MichaelYusko** [comment]
@josephmancuso Yeah, sure! I'll start work on the ticket since tomorrow/sunday. and the same for the slack channel:)

**Comment by josephmancuso** [comment]
@MichaelYusko How are you on this feature? Need any help?
