### ISSUE TITLE
What is the purpose of api.py?

### ISSUE THREAD

**Issue by 3lpsy** [MasoniteFramework/masonite#96]
So when i run ``` craft show:routes ```, the RESOURCES variables in api.py is not included. In addition, the RouteProvider does not seem to load the api routes. I'd be willing to work on integrating the API routes into the framework such as modifying the RouteProvider to load the correct middleware. It just doesn't seem like api.py does anything.

**Comment by josephmancuso** [comment]
You're right the api route actually for the api package that installs with the framework but is commented out by default.

**Comment by josephmancuso** [comment]
Check the providers list and there should be a commented out line of code in that list

**Comment by josephmancuso** [comment]
sorry i was on mobile before. So for a more detailed explanation: The API stuff was more integrated with Masonite 1.6 (the previous release of Masonite). So for 2.0 I commented out the provider and actually sort of refactored the API library (called Masonite Entry). 

The API library isn't the best. Usually the libraries I build for Masonite come from necessity of needing them for projects I am making. The API sort of came out of what I think the library should have instead what i need. I think its still a decent library but it likely needs to be updated out of necessity.

If working with API's is something your are familiar with and want to make it work with Masonite then I'd be happy to team up and talk about any ideas you have for changing it.

**Comment by 3lpsy** [comment]
Yeah, I'm very interested in helping out (though I only started looking at masonite a few days ago). I used to be a Laravel dev and have been doing python dev (flask/django) for about two years now so this project is very interesting to me. I'm going to familiarize myself with the core framework first, but let me know if there's an irc/chat room for masonite devs.

**Comment by josephmancuso** [comment]
slack.masoniteproject.com

**Comment by josephmancuso** [comment]
For the past couple of days I've been working on redoing all the docstrings on every class so there soon should be some really awesome API Reference documentation for you to read to familiarize yourself with specific classes
