### ISSUE TITLE
Masonite website, slack channel, and docs urls are non-functional

### ISSUE THREAD

**Issue by breisfeld** [MasoniteFramework/masonite#99]
As of now, the urls that point users to the main site, docs, and slack channels are non-functional:

http://slack.masoniteproject.com: `This site can’t be reached`

https://docs.masoniteproject.com: `This site can’t be reached`

http://masoniteproject.com: `2018 Copyright. All Rights Reserved. The Sponsored Listings displayed above are served automatically by a third party. Neither Parkingcrew nor the domain owner maintain any relationship with the advertisers. Privacy Policy`

**Comment by josephmancuso** [comment]
🤔 
Weird. looks like the DNS is down. Let me check on it! Thanks!

**Comment by josephmancuso** [comment]
looks like namecheap somehow reset all the DNS settings ... 😠 

I recently purchased email through them so it looks like a bug with them .. 

Thanks for the report!

**Comment by breisfeld** [comment]
That did the trick. Thanks!
